### ISSUE TITLE
Incompatible with newer gradle versions

### ISSUE THREAD

**Issue by MulverineX** [Barteks2x/CubicChunks#105]
I downloaded the repo, opened up cmd in admin (I have gradle installed) and the it failed with this error
`Execution failed for task ':compileJava'.
> Could not get unknown property 'refMaps' for task ':jar' of type org.gradle.api.tasks.bundling.Jar.`
[gradlelog.txt](https://github.com/Barteks2x/CubicChunks/files/597411/gradlelog.txt)

**Comment by Niko-sk2x** [comment]
1. I don't know which gradle task it is
2. You downloaded the zip and used that, without git repository version will be incorrect. I tried to make it work but I might break it recently
3. There are currently a few bugs that make it very unstable and I'm in the process of updating it to MC 1.11.

**Comment by Niko-sk2x** [comment]
Also, use gradle wrapper. Don't use your own gradle version. I won't support gradle versions different than the one used by my gradle wrapper.

**Comment by Niko-sk2x** [comment]
And don't run things as admin. It's unnecesary and unsafe. If something breaks when you don't run it as administrator, complain to them.

**Comment by Niko-sk2x** [comment]
Closing it as invalid for now, if you still have the issue - comment here with more ifnormation about what and how you did and I will reopen it

**Comment by Niko-sk2x** [comment]
I got the same issue when trying to update to gradle 3.2

**Comment by Niko-sk2x** [comment]
Fixed in 819b17a6e0adbc55d559d5dd3d0f15ddbf4ba712

Needs gradle 3.2 now
