### ISSUE TITLE
Some Columns are not unloaded serverside

### ISSUE THREAD

**Issue by Barteks2x** [Barteks2x/CubicChunks#11]
Some empty columns that appear outside of the view radius do not get unloaded

**Comment by Cyclonit** [comment]
This happens without the dependeny system being engaged at all.

**Comment by Barteks2x** [comment]
After some debugging, it turns out I probably got Column.enqueueRelightChecks wrong and it causes new columns to be loaded.

**Comment by Barteks2x** [comment]
It looks like these chunks are also getting loaded in vanilla, but they are somehow getting unloaded after some time. And the cycle repeats.

**Comment by Barteks2x** [comment]
Fixed in 3a6b9e991fe6cef6a72a1d10383b968722ae92d2
