### ISSUE TITLE
Find new name and (maybe?) move to organization account

### ISSUE THREAD

**Issue by Niko-sk2x** [Barteks2x/CubicChunks#116]
The CubicChunks name is already used by the original Robinton's mod, and reusing it may not be a good idea (even if allowed).

Any suggestions? I will write some suggestions I got or came up with myself (in separate replies to that they can be upvoted separately)

**Comment by Niko-sk2x** [comment]
Vertical Chunks

**Comment by Niko-sk2x** [comment]
Vertical Expansion

**Comment by Niko-sk2x** [comment]
3D chunks

If it didn't start with a digit (which will cause issues) I think it would be the best one.

**Comment by Niko-sk2x** [comment]
Vertically Unlimited

**Comment by Niko-sk2x** [comment]
Cubic Chunks Reborn

**Comment by theishiopian** [comment]
Mojang's reckoning?

**Comment by JonL98** [comment]
"Atlas Shrugged" (Might want to look up copyright laws on that)
"Atlas Unbound"

**Comment by JonL98** [comment]
Might want to look up copyright laws on that though.

**Comment by theishiopian** [comment]
Chunks^3

**Comment by xcube16** [comment]
BetterChunks

**Comment by theishiopian** [comment]
Chunks++? (C++ for short )

**Comment by Niko-sk2x** [comment]
It's also possible that the name will be left unchanged, if I confirm that I'm actually allowed to use it and it won't be a problem.

**Comment by Quizer9O8** [comment]
If I was you I should keep the name the same. It can't get any better than CubicChunks for now...
Or you can name it InfinityChunks, FinityChunks.

Oh I got a good one as undertitle:
CubicChunks
(The Last Chunk Bender)

**Comment by J0celyn22** [comment]
I agree with Quizer9O8, the name CubicChunks is great, so keeping it in the name would be a good idea. Therefore, the "CubicChunks Reborn" idea was good. Maybe Reforged instead of reborn would do it too, like the new Conquest mod.
I also like "The Last Chunk Bender" as undertitle. And I have an idea of "slogan" even if it is completely useless ^^ : "The sky is not a limit"

**Comment by Niko-sk2x** [comment]
J0celyn22 you are not the first who came up with "the sky is not a limit". Robinton wrote in description of his mod "The sky is no longer the limit". I actually wanted to add it as one of those random messages that appear in main menu.

Currently I'm waiting for Robinton to decide if it would be ok to use the name cubic chunks here (probably nothing would happen if I did, but I want to be sure).

**Comment by Terran-Rockefeller** [comment]
Sky's The Limit.

'nough said.

**Comment by Pitigoi** [comment]
"Actually infinite" sounds kind of sassy,but who am i to say?

**Comment by Niko-sk2x** [comment]
For now sticking with the name cubic chunks. If it ever becomes an issue, this will be reopened.
