### ISSUE TITLE
Chunks not rendering from certain positions above max height/below min height

### ISSUE THREAD

**Issue by Niko-sk2x** [Barteks2x/CubicChunks#118]

**Comment by BaccarWozat** [comment]
This occasionally happens to me when flying up while looking down, when reaching Y=256. The chunks above 256 do not render and I get stuck; I can look around with the mouse but the keyboard movement does nothing. I can still go into options or inventory, and sometimes I can teleport, but usually I have to relog to fix this.

**Comment by Niko-sk2x** [comment]
That looks like a completely different issue with server not sending the chunk you are in to client. These should be fixed long ago. I wasn't able to make it happen so I will son send you a special version of the mod that will generate possibly huge log file that shows what is happening. And report it as separate issue.

**Comment by Niko-sk2x** [comment]
Already fixed.
