### ISSUE TITLE
Terrain generation events in CustomCubic

### ISSUE THREAD

**Issue by Niko-sk2x** [Barteks2x/CubicChunks#120]
With the way most of these forge events work, it may be impossible to implement most of them (they need chunk pos and mods may be confused about the same event being fired many times for the same chunk).

**Comment by Foghrye4** [comment]
Currently to generate ores modders create they own world generators classes by implementing IWorldGenerator interface and register instances of them in GameRegistry.

So here is a plan: 1. Create interface ICubicWorldGenerator.
2. Modders optionally will implement them in they own world generators.
3. On calling ```public void populate(Cube cube)``` detect whenever GameRegistry contain instances of ICubicWorldGenerator and call a function.

Second option: create our own registry.

**Comment by Niko-sk2x** [comment]
There should be some optional compatibility layer that will allow existing vanilla generators to work for height range 0-256, custom CubicWorldGenerators will be pat of the API

**Comment by Foghrye4** [comment]
> optional compatibility layer that will allow existing vanilla generators to work for height range 0-256

1. Detect if cube is a first in a column of 16. 
2. Lock calling world generators in other cubes (should be NBT saved value).
3. Generate cube whenever ```setBlock``` is called for not yet generated cubes.

**Comment by Niko-sk2x** [comment]
the thing is they will try to get the top block, which will give them currently generated top block. So the 16 cubes need to be generated ahead of time, before firing the events

**Comment by Foghrye4** [comment]
@Barteks2x I see a "Vanilla compatibility generator" already do it. You want flat and custom cubic to do a same things?

**Comment by Niko-sk2x** [comment]
Maybe not yet, this is more like a long term plan for compatibility. I fiirst need to make world generation faster.

**Comment by Niko-sk2x** [comment]
The option is already added
