### ISSUE TITLE
FML Update Causing Exception Crash When Launching

### ISSUE THREAD

**Issue by weidncol** [Barteks2x/CubicChunks#121]
Upon compiling and attempting to run the Minecraft Client through gradle, there is a few exceptions causing it to crash with an Exception in thread "Client Thread" error. Attached is the FML log.

[fml-client-latest.txt](https://github.com/Barteks2x/CubicChunks/files/674628/fml-client-latest.txt)

**Comment by Niko-sk2x** [comment]
How *exactly* did you run the mod?

It works fine for me, even when running using `gradlew runClient` on windows,

**Comment by Niko-sk2x** [comment]
~~Also you clearly didn't run it from gradle, I see IDEA jar in classpath.~~ unless you are talking about `GradleStart`

**Comment by weidncol** [comment]
Yes, I meant the `GradleStart` as the main class for my Minecraft Client application I made to run it. 

I'm running the mod through IDEA as a Application Run Configuration, which worked great for me the past two versions of the mod I've been using.

**Comment by Niko-sk2x** [comment]
What are your VM options and program arguments?

**Comment by weidncol** [comment]
I'm using `-Dfml.coreMods.load=cubicchunks.asm.CubicChunksCoreMod -Dmixin.env.compatLevel=JAVA_8` as my VM options with no program arguments. My MalisisCore version is 1.11-5.0.0

**Comment by Niko-sk2x** [comment]
Exact MalisisCore build may also be a bit different, I don't know any way to get the exact build information from it, so could you upload file:
`C:\Users\User\.gradle\caches\modules-2\files-2.1\net.malisis\malisiscore\1.11-5.0.0-SNAPSHOT\df4d71c26b6747be025df93ae2d10ad9194a67e7\malisiscore-1.11-5.0.0-SNAPSHOT-dev.jar`?

**Comment by Niko-sk2x** [comment]
(Wrong button)

**Comment by weidncol** [comment]
[malisiscore-1.11-5.0.0-SNAPSHOT-dev.zip](https://github.com/Barteks2x/CubicChunks/files/676089/malisiscore-1.11-5.0.0-SNAPSHOT-dev.zip)

**Comment by Niko-sk2x** [comment]
It works for me even when I use the same version. Did you re-run setupDecompWorkspace after updating to this version? This version adds a new dependency that has access transformers, and changing access transformers requires re-running setupDecompWorkspace.

I would expect different error but it won't hurt to do that.

**Comment by weidncol** [comment]
Nope, I sure didn't! That seemed to do the trick! Thank you very much.
