### ISSUE TITLE
Split the mod into smaller modules

### ISSUE THREAD

**Issue by Niko-sk2x** [Barteks2x/CubicChunks#135]
Currently planned modules:
 * Core - contains all mixins necessary for the mod to work, and cubic chunks debug world type, with all the necessary code to make cubic chunks world types work
 * VanillaCubuc - VanillaCubic world type, may also allow to turn any world into cubic chunks world
 * CubicGeneratorApi - advanced world generation API
 * CubicGeneratorsBase - FlatCubic and CustomCubic
 * ??? - other modules with more world generators and additional features

**Comment by JonL98** [comment]
With the amount of extra space that this mod gives, world generation and biomes have a chance to improve substantially. Mt. Everest, for example, is almost 30,000 meters high, the Rhine river, 7 million. What if terrain features in MC suddenly so massive and diverse that it becomes almost 1:1 with real earth terrain? 
This would, of course, require some tweaks to the rendering. There are theories that use polygon meshes to increase render distance, but ultimately, they're all a bit of a longshot with Java. I saw a tweak though for MC Windows 10, which is C++, that extended the view distance almost infinitely.

**Comment by Niko-sk2x** [comment]
The problem with extreme view distance isn't rendering itself, it's loading that insane amount of chunks you would need. Also replicating real world like terrain would require completely rewriting biome generation and how biome properties are used to determine terrain.

What could be done for rendering is large scale mesh based not on generating more and more chunks, but metadata stored with the terrain and for ungenerated chunks - data that could be provided by terrain generator. This is actually doable, maybe as yet another module. Rendering something like that would completely ignore TESR-based blocks, but model-based blocks could be still rendered in some approximate form.

This is very low priority for the base mod, and there is way more stuff to do before that. But if someone wants to work on it - I would be happy to work on splitting the mod into modules very soon and provide information about how it could be done.

But even then it definitely won't be part of the main mod, it is going to be separate.

**Comment by JonL98** [comment]
Yeah, I figured it'd be a very distant future addition and definitely a separate module. Just letting slip my delusions of grandeur, I suppose.

**Comment by Foghrye4** [comment]
Benefits: 
1. Players can decide what module to download, therefore slightly increase Minecraft load speed and slightly reduce memory usage.


Disadvantages: 
1. Downloading 2 or 3 or 4 modules instead of 1 single mod is bloody annoying.
2. If you give your permission for modpacks, it ends up in some modpack with all modules.
3. You will waste your time on a feature, which is nobody need.
See Forestry as example,

A thing which is really necessary - is API for addon creation.

**Comment by Niko-sk2x** [comment]
By default there would be a prepackaged "-standard" and/or "-all" jar file, the standard one would contain what most players will likely need/want. 

As for modpack permission - I think not giving permission is stupid anyway. Why a mod exists if you can't use it together with other mods?

There won't be a lot of deafult modules. Basically only what is already there. World generators will be separate. The main purpose of splitting them is that it will be possible to update them separately, which means we can get `core` working with new Minecraft version that breaks a lot of things without also updating world generators at the same time.

Since there isnt really much we are doing at load time (other than Mixin transforming classes) - it won't noticably improve loading speed.

**Comment by Niko-sk2x** [comment]
Already done.
