### ISSUE TITLE
ServerHeightMap/OpacityIndex: Remove the opacity bit from segments

### ISSUE THREAD

**Issue by Niko-sk2x** [Barteks2x/CubicChunks#139]
The opacity bit is completely redundant (values are always alternating between 0 and 1) and is left there only because it was like that back when full opacity value was stored.

To avoid possible corruption, the code can be modified to pack segment pairs into longs. Corrently the amount of segments is always odd number, so "fix" that, either minY or maxY could be removed and made part of segments. This would make amount of segments always even without increasing the amount of used memory (4 bytes more per x/z column in segments, but also 4 bytes less for minY/maxY array).

**Comment by Cyclonit** [comment]
@Barteks2x this can be closed.

**Comment by Niko-sk2x** [comment]
Right, I forgot to close it.
