### ISSUE TITLE
Putting blocks beyond current limit

### ISSUE THREAD

**Issue by ghost** [Barteks2x/CubicChunks#148]
Is it possible to change the current limit (8 million blocks) to the maximum 32-bit integer? I searched the code and there wasn't any code with the 8 milllion blocks limit. Does this needs rewriting the save format?

**Comment by Niko-sk2x** [comment]
The only place still limited to 8 million blocks up and dow (24 bits for Y) is ServerHeightMap, and it's only because of how it used to work and I still didn't remove that limit. Save format has been changed already (but there are still more changed planned).

**Comment by Niko-sk2x** [comment]
Other problem with such extreme heights is that there are some rendering issues. And last time I removex X/Z limits and tried to teleport close to Integer.MAX_VALUE even frustom culling stopped working correctly.

**Comment by Cyclonit** [comment]
~~Just as a side note, why would you want this? I think 16mil blocks in total is sufficient. I don't want to discourage removing unnecessary limits, but if having them makes other things easier, they should stay.~~

**Comment by Niko-sk2x** [comment]
I will remove the limit anyway together with other changes to ServerHeightMap (when I remove the boolean flag stored in ServerHeightMap, it's unnecessary because it always alternates between true and false anyway, odd positions always have one value, even positions always have the other value, I will store a pair of values in a single 64-bit value). The game will probably crash a few hundred blocks away from Y = Integer.MIN/MAX_VALUE so there has to be some limit.

**Comment by ModForge** [comment]
I want to remove the limit for testing. Can I just change the value of the limit? Thanks for help.

**Comment by Niko-sk2x** [comment]
Changing the limit may break lighting in some way but everything else should work. Unless there are some remaining usages of AddressTools

**Comment by ModForge** [comment]
Lighting is not issue to me.

**Comment by Niko-sk2x** [comment]
It would break height map so it may even crash

**Comment by ModForge** [comment]
I will try to change the 24 bit value to 32 bit to see if it crashes.

**Comment by Niko-sk2x** [comment]
I changed ServerHeightMap already, and after changing the height limit used in code, Minecraft was playable at y=-1,000,000,000 (after the most recent fixes to avoid server freezing). Removing the last bit to use full 32 bits of height requires chaging more of ServerHeightMap (and I will do the changes that allow it but for different reason). Also setting limis to anything within about 4096 blocks of min/max int values will result in integer overflows in some places.

**Comment by ModForge** [comment]
Thanks for everything. I couldn't do it myself. So I will wait.
