### ISSUE TITLE
Make CubicSaveHandler a mixin

### ISSUE THREAD

**Issue by Niko-sk2x** [Barteks2x/CubicChunks#157]
Mods may assume that Minecraft ISaveHandler is always instance of SaveHandler, cubic chunks currently breaks this assumption.

**Comment by Niko-sk2x** [comment]
~~Closed by ccfd8af20c757bc53315c03d21c3107d7075b3cf~~

**Comment by Niko-sk2x** [comment]
Closed wrong issue

**Comment by Cyclonit** [comment]
Afaik this has already happened? The interface ICubicSaveHandler is used for a mixin in AnvilSaveHandler and redirects calls to ICubeIO

**Comment by Niko-sk2x** [comment]
Yes, can be closed.
