### ISSUE TITLE
Error compiling the mod

### ISSUE THREAD

**Issue by MobiusFlip** [Barteks2x/CubicChunks#160]
When trying to compile with "gradlew build":

> A problem occurred configuring root project 'CubicChunks'.
> One of setGitDir or setWorkTree must be called.

**Comment by Niko-sk2x** [comment]
You downloaded the mod as zip file. I started investigating it a while ago, and I came to the conclusion that it doesn't make sense to support it anymore. 

The only way you can get source without git repository is if you download it as zip file. And the downloaded zip file doesn't contain RegionLib submodule, which is needed to compile the mod.

Just install git and clone the repository, as I explained in readme.
