### ISSUE TITLE
Birch, Acacia, Jungle 2x2, Spruce 2x2, Dark Oak 2x2 Sapplings do not grow beyond Y:256 / Y:0

### ISSUE THREAD

**Issue by Quizer9O8** [Barteks2x/CubicChunks#163]
![2017-02-12_10 09 22](https://cloud.githubusercontent.com/assets/19509275/22860920/a8d97104-f10b-11e6-9fb7-b43c5093ce56.png)
Besides that none of the saplings (except Oak but it takes way to much bone to grow) do grow below Y:0
![2017-02-12_10 19 41](https://cloud.githubusercontent.com/assets/19509275/22860953/d327c900-f10c-11e6-89bf-352ae0050721.png)
)

**Comment by Niko-sk2x** [comment]
That was supposed to be part of #15 but I will keep it here separately

**Comment by Niko-sk2x** [comment]
Fixed with recent changes in ce93216bc427a07b333f1fe165e3368670799e21 and 2f83bf2c5daef7cf59372dafcf08728b0693508d
