### ISSUE TITLE
Bat AI confused.

### ISSUE THREAD

**Issue by Quizer9O8** [Barteks2x/CubicChunks#164]
The Bat keeps flying in the same spot.
![2017-02-12_10 25 29](https://cloud.githubusercontent.com/assets/19509275/22860996/1d8ab5ec-f10e-11e6-89b4-48f4bd9b76b8.png)

**Comment by Niko-sk2x** [comment]
Are you sure the server isn't frozen? It seemed to work for me even at extreme depths.

**Comment by Niko-sk2x** [comment]
I found the code responsible for this:
```java
            if (this.spawnPosition != null && (!this.world.isAirBlock(this.spawnPosition) || this.spawnPosition.getY() < 1))
            {
                this.spawnPosition = null;
            }
```
It's not literally stopped in one place, it just doesn't fly very far.
