### ISSUE TITLE
[Config Option] spawn lava caves, ravines and caverns at Y: ...

### ISSUE THREAD

**Issue by Quizer9O8** [Barteks2x/CubicChunks#165]
Y:11 used to be the lava level but since the height changed there is no lava to be found. it has become a rare thing to find.
![2017-02-12_10 38 24](https://cloud.githubusercontent.com/assets/19509275/22861053/700fe9e4-f10f-11e6-8328-6a0f4587a639.png)

**Comment by Niko-sk2x** [comment]
Part of #15

**Comment by Niko-sk2x** [comment]
Ravines already have lava. The deeper you go, the more lava they have.
