### ISSUE TITLE
(Custom Cubic) Ocean floor made completely out of dirt/clay patches instead of full gravel

### ISSUE THREAD

**Issue by Quizer9O8** [Barteks2x/CubicChunks#166]
Also caves are breaking up the ocean floor like this.
![2017-02-12_10 40 36](https://cloud.githubusercontent.com/assets/19509275/22861065/d50ee5a2-f10f-11e6-9d3b-fe6f40d5d155.png)
![2017-02-12_10 41 12](https://cloud.githubusercontent.com/assets/19509275/22861066/d513e606-f10f-11e6-8f48-17e8000367c7.png)

**Comment by Niko-sk2x** [comment]
Part of #15.
