### ISSUE TITLE
Skeleton AI confused after the Wither attacks

### ISSUE THREAD

**Issue by Quizer9O8** [Barteks2x/CubicChunks#168]
It keeps running in circles and shooting arrows everywhere...
![2017-02-12_10 56 08](https://cloud.githubusercontent.com/assets/19509275/22861150/24846efc-f112-11e6-873f-7e3bd7086fd4.png)

**Comment by Niko-sk2x** [comment]
That seems weird, does it also happen in vanilla height range?

**Comment by Niko-sk2x** [comment]
Also, when you make screenshots in dark places - either increase contrast & brightness, or use night vision potion.
This is what your screenshot looks like after increasing brightness and contrast:
![24846efc-f112-11e6-873f-7e3bd7086fd4](https://cloud.githubusercontent.com/assets/1349112/22863308/f5e78274-f13d-11e6-9d38-249da1c3de8c.png)

**Comment by Niko-sk2x** [comment]
~~No idea how did you manage to make it happen, the withers are flying away all in the same direction ignoring the skeletons. And that one skeleton they did accidentally attack didn't really reach, it just died.~~ I was able to reproduce it
