### ISSUE TITLE
Game crashes after clicking the "customize" button under world type "Custom Cubic" (missing dependency)

### ISSUE THREAD

**Issue by Hanro50** [Barteks2x/CubicChunks#171]
Selecting the world type "Custom Cubic" and then clicking the "customize" button that appears will crash Minecraft

**Comment by Niko-sk2x** [comment]
I forgot to add MalisisCore as dependency to mcmod.info so it doesn't tell you that the dependency is missing, and it's needed only in customization GUI. You need to add MalisisCore 1.11.2-5.0.2-SNAPSHOT mod (you can find it [here](https://oss.sonatype.org/content/repositories/public/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/))

**Comment by Hanro50** [comment]
thanks...
BTW, I really enjoyed the mod and I'm looking forward to the possibilities it can open in the future
