### ISSUE TITLE
Build Height Limit on server

### ISSUE THREAD

**Issue by GoldenEpsilon** [Barteks2x/CubicChunks#176]
This will probably be a quick one - on the server, it is a cubic chunks world (for example, no bedrock), but it still doesn't let me build above 255. I'm guessing this is a thing that was added client side but not server side. Thanks!

(oh, you don't have to answer this, but what's the world type called internally, so I can spawn it from server.properties without drag/dropping my save file?)

**Comment by Niko-sk2x** [comment]
The world type is the generator type. Change `DEFAULT` to `VanillaCubic` or `CustomCubic` or `FlatCubic`

As for the 256 limit - can you create blocks above that limit using commands? I remember there was an issue with building exactly *at* y=255. And it may be the build height in server.properties not being changed.

**Comment by GoldenEpsilon** [comment]
Ohhhhhh there IS a build height in server.properties! why does that exist >.<
Well, thank you!

**Comment by Niko-sk2x** [comment]
Note that build height in `server.properties` is NOT the same as world height stored in NBT. Build height is the height accessible for players to build with, trees for example can still grow higher, but it will be impossible to break them for players (that's how it works in vanilla)
