### ISSUE TITLE
Mobs have too dark shadows from certain positions/angles

### ISSUE THREAD

**Issue by Niko-sk2x** [Barteks2x/CubicChunks#181]
![2017-05-20_01 58 00](https://cloud.githubusercontent.com/assets/1349112/26270933/f3ae0eb6-3cff-11e7-87e0-0e157e13c10c.png)

**Comment by GoldenEpsilon** [comment]
Could this be the same as the dark entities bug from earlier?

**Comment by Niko-sk2x** [comment]
That was the whole entities rendering dark, that was something else. And I already made the same bug impossible.

**Comment by Niko-sk2x** [comment]
Seems to be fixed as of https://github.com/OpenCubicChunks/CubicChunks/commit/6b788cefd7622b51445bc1b7d66fb949cb941262
