### ISSUE TITLE
Compability with OptiFine

### ISSUE THREAD

**Issue by ghost** [Barteks2x/CubicChunks#182]
Just what the title says. This mod crashes with optifine. I think it's about something with rendering system. I can put the crash report if needed.

**Comment by Niko-sk2x** [comment]
Nope. That's definitely too much work. Maybe if optifine was open source.

**Comment by Niko-sk2x** [comment]
If you want more detailed explanation for "why":

Optifine a CubicChunks toucha  lot of the same code in different ways. I would have to go through optifine code and add special optifine-only Mixins, and possibly even modify OptiFine code. Some optifine features would probably even have to be removed. But optifine isn't open source. A lot of the code I woukld get probably wouldn't be very readable, I would have no comments, no documentation.

I will investigate that possibility, but it's unlikely I will ever make cubic chunks optifine-compatible. 

If you want OptiFine compatibiliy - do it yourself and submit PR, or ask someone else.

**Comment by Niko-sk2x** [comment]
Done in https://github.com/OpenCubicChunks/CubicChunks/commit/8c08f794de844bc2c2d652a80b6b8aa3f86db94d
