### ISSUE TITLE
Make ServerHeightMap work with full 32-bit integer range

### ISSUE THREAD

**Issue by ghost** [Barteks2x/CubicChunks#183]
I know I created a issue about this already but I finally changed serverheightmap to make it use 32-bit integers. But when compiling it says that there is problem with "test". What can I do to fix this?

**Comment by Niko-sk2x** [comment]
This means that you broke ServerHeightMap by doing it. There is a good reason ServerHeightMap only uses 31 bits. It *can* be fixed byt as noone is ever going to use even 31 bits, I doubt doubling the height from 1 billion up and down to 2 billion up and down would make any difference.

**Comment by ModForge** [comment]
Just curious about what happens when you reach that point

**Comment by Niko-sk2x** [comment]
The game will crash when you rwach max integer. I already did it horizontally once because I was also curious.

**Comment by ModForge** [comment]
Ok then

**Comment by ModForge** [comment]
Wait what if we use 64 bit integers and put a block on the 33 bit limit?

**Comment by Niko-sk2x** [comment]
Also, this is duplicate of #139
