### ISSUE TITLE
Malisiscore not recognized

### ISSUE THREAD

**Issue by BaccarWozat** [Barteks2x/CubicChunks#186]
Using either CC 0.0.554.0 or 0.0.557.0, and either MalisisCore 5.0.0 or 5.1.1, the game refuses to start because it says "MalisisCore 5.0.0 or earlier not detected".

https://pastebin.com/pA7C0BZK

**Comment by Niko-sk2x** [comment]
Oops, that's a small mistake. Instead of  `[5.0.0,)` I have `[,5.0.0)`

**Comment by Niko-sk2x** [comment]
in the meantime you can run the mod without malisiscore, you just won't have access to custmization gui.
