### ISSUE TITLE
Buildcraft Pipe Connectivity At Y>255

### ISSUE THREAD

**Issue by BaccarWozat** [Barteks2x/CubicChunks#189]
CC 0.0.567.0 and BC 7.99.3.

At Y>255, especially around the chunk edges, BC pipes don't always connect, or take their time in autoconnnecting (not sure if it's a tick speed problem). The problem seems to get worse at greater heights. The blocks flew right out of the pipes, showing they were not actually connected.

I flew down and back up and some of the pipes connected, but I got this strange unknown block which is the shape of a mining well segment where a cobble pipe should be. I couldn't break it or identify it in WAILA.

![2017-05-24_00 10 15](https://cloud.githubusercontent.com/assets/8357501/26393855/bd30d146-4030-11e7-9aa5-797a3bfd9ad5.png)
![2017-05-24_00 29 13](https://cloud.githubusercontent.com/assets/8357501/26393857/bd3c73de-4030-11e7-8d7a-6aa17eef5690.png)
![2017-05-24_00 34 21](https://cloud.githubusercontent.com/assets/8357501/26393856/bd383440-4030-11e7-8cc9-b61a81a44aff.png)

**Comment by Niko-sk2x** [comment]
Until it's properly fixed in BuildCraft I will probably make my own fork of it and fix it there, orcreate special mod that poatches it at runtime.

**Comment by Niko-sk2x** [comment]
Fixed in BuildCraft/BuildCraft@9b9b10f
