### ISSUE TITLE
Chunk Error when Generating World

### ISSUE THREAD

**Issue by MatthewTNT79** [Barteks2x/CubicChunks#193]
I generated a new world in VanillaCubic and there was a chunk error as the world was generating.
https://www.dropbox.com/s/hxfq211q323kv3h/2017-05-25_19.42.07.png?dl=0

**Comment by Niko-sk2x** [comment]
This is "just" one chunk generating with wrong seed/position given to  the generator.

**Comment by Niko-sk2x** [comment]
The only explanation I can find is that this is vanilla bug, caused by concurrency issue when cliet attempts to generate it's own biomes before server sends any chunks.

**Comment by Niko-sk2x** [comment]
I'm almost sure this is vanilla booms generation bug causing it.. Closing for now.. Comment here if it happens again.
