### ISSUE TITLE
Worlds Fail To Load

### ISSUE THREAD

**Issue by MatthewTNT79** [Barteks2x/CubicChunks#194]
In the latest version of this mod, any world, whether it's new, a vanilla, or cubic chunks worlds gets stuck on the loading screen when it loads.

**Comment by MatthewTNT79** [comment]
I have a log here.
https://www.dropbox.com/s/xs9q7b69s103obx/2017-05-25-7.log.gz?dl=0

**Comment by Niko-sk2x** [comment]
This log just basically says "starting Minecaft" and "Stopping Minecraft". You aren't loading any world there.

**Comment by Niko-sk2x** [comment]
Is this issue still relevant? Closing it for now, comment here if you want it reopened

**Comment by 1971chevycamaro** [comment]
its still loading world for me, is it supposed to take >10 minutes?

**Comment by Rongmario** [comment]
Depends what mods you have, some mods worldgen isn't compatible with CC worlds. Please open a new issue though.

**Comment by Niko-sk2x** [comment]
If anyone gets the same issue again, please open a new issue instead of commenting here.
