### ISSUE TITLE
/fill complains about placing blocks outside world below y = 0 or above 255

### ISSUE THREAD

**Issue by bluebear94** [Barteks2x/CubicChunks#196]
When you try to place blocks below y = 0 or above y = 255 with `/fill`, then you get an error message saying `Cannot place blocks outside world`.

**Comment by BaccarWozat** [comment]
I got it to work, with a bit of a delay, for Y=257, but it gets the error message at Y=2048. Commands used were
`/fill 300 257 150 350 257 200 stone`
and
`/fill -50 2048 -50 50 2048 50 dirt`
Worse, the 257 behavior cannot be replicated, and now I am getting the error message at BELOW Y=256 and as low as Y=96. It might have something to do with the number of blocks to place, or it could be whether there had already been an error displayed.
![2017-05-27_22 42 40](https://cloud.githubusercontent.com/assets/8357501/26525978/6e0e4476-432e-11e7-8555-9804994efcac.png)

**Comment by Niko-sk2x** [comment]
It's probably the wrong constant being replaced somewhere.

**Comment by Niko-sk2x** [comment]
Turns out vanilla has some **really** strange logic there:

it checks if the block at Y=(maxFillY - minFillY) is loaded.
