### ISSUE TITLE
The Second End Portal Freezes The End

### ISSUE THREAD

**Issue by MatthewTNT79** [Barteks2x/CubicChunks#199]
I went into the end, defeated the dragon, left the end, and quit the world. When I went back in, I went back to the end and threw an enderpearl in the second portal that appears. After that, everything but the player froze. The endermen were still and didn't interact with me, the enderpearl didn't work anymore and neither did the portal. And when I tried to quit the world, Minecraft stopped responding.
https://www.dropbox.com/s/i21fbzmh54xtle0/fml-client-latest.log?dl=0

**Comment by Niko-sk2x** [comment]
should be fixed in https://github.com/OpenCubicChunks/CubicChunks/commit/f76103fd16468f0b11d7a9b8c089999514073bda

**Comment by Niko-sk2x** [comment]
Wrong issue
