### ISSUE TITLE
UtilityWorlds compatibility

### ISSUE THREAD

**Issue by BaccarWozat** [Barteks2x/CubicChunks#201]
Using Forge 2309, CC 581 and [UtilityWorlds](https://minecraft.curseforge.com/projects/utility-worlds) 1.1.0. The worlds themselves (mining, void and garden) all work fine, generating no terrain in void and a superflat in the other two. The portals work fine when first traveling to the worlds. When using the return portal, however, I went back exactly where I was, except no terrain was generated, I couldn't move or fly anywhere, and F3 said I was "Outside of world". I had to /tp out of range of rendering in order to start generating chunks again.

The minimap (Xaero's) and its waypoints are unusable when "out of world", but work again the moment I /tp successfully. Without the minimap installed I get the same portal results.

Latest.log (no crash) - https://pastebin.com/WvDX8RJ1

What the portal blocks normally look like:
![2017-05-28_03 36 50](https://cloud.githubusercontent.com/assets/8357501/26527354/f4fc725e-4357-11e7-85e2-bd3656cf6f05.png)

What it looks like when I get back:
![2017-05-28_03 24 30](https://cloud.githubusercontent.com/assets/8357501/26527355/f8f40548-4357-11e7-95ef-a60ffbdedeaa.png)

**Comment by Niko-sk2x** [comment]
How many times do I have to say that `latest.log` is *not* useful for me?

`latest.log` contains only `INFO` and higher log level. I need `DEBUG`/`TRACE` log level, which is in `fml-client-latest.log`

**Comment by Niko-sk2x** [comment]
This is apparently something very wrong when going between dimensions.

**Comment by BaccarWozat** [comment]
fml-client-latest.log now has something else, but here's fml-client-1.log which ought to have at least some of what you want. (2 apparently does not.)
http://depositfiles.com/files/7245awgmj

**Comment by Niko-sk2x** [comment]
Now that is some shady website... next time, coud you use something like dropbox?

**Comment by Niko-sk2x** [comment]
Should be fixed in https://github.com/OpenCubicChunks/CubicChunks/commit/f76103fd16468f0b11d7a9b8c089999514073bda. Comment here if it's not.
