### ISSUE TITLE
Nether portal generated too far from player

### ISSUE THREAD

**Issue by BaccarWozat** [Barteks2x/CubicChunks#208]
Got into the nether portal at Y=2695 with no problem. Spawned inside netherrack at Y=2695 which had to be manually broken, and no return portal in sight. And it didn't generate at 336 (~Y÷8) but rather at **120**.

I couldn't find anything in fml-client-latest.log that referenced portal generation.

Edit: After I came back from the nether, I went through the portal again, and this time it spawned the portal at 2695 where I had originally been sent. This seems to be because I had dug out a space the last time. So the code appears to also require air blocks.

![2017-05-31_20 56 33](https://cloud.githubusercontent.com/assets/8357501/26661870/e364d23e-4645-11e7-924a-bcf0c003ff8b.png)
![2017-05-31_20 57 09](https://cloud.githubusercontent.com/assets/8357501/26661869/e3604372-4645-11e7-8031-ea662fa6f179.png)
![2017-05-31_21 09 33](https://cloud.githubusercontent.com/assets/8357501/26661868/e35d4a1e-4645-11e7-86cb-cc7ebdb2674d.png)

**Comment by Niko-sk2x** [comment]
Could you upload a log anyway? It may be that some mixin failed to apply.

**Comment by BaccarWozat** [comment]
You got it.
https://pastebin.com/DQZ7fYWf
Much of it was testing the UtilityWorlds portals (those work perfectly fine now, btw).
