### ISSUE TITLE
Some formerly required cubes do not get removed from the DependencyManager after all dependents have been unregistered.

### ISSUE THREAD

**Issue by Cyclonit** [Barteks2x/CubicChunks#21]
#18 
The cubes are no longer present in the ServerCubeCache.

**Comment by Cyclonit** [comment]
Some cubes are not being unregistered prior to being registered anew. This may lead to the old requirements being forgotten.

**Comment by Cyclonit** [comment]
Fixing this caused no rogue cubes to show up thus far. I'll do some more testing to be sure.

**Comment by Cyclonit** [comment]
Testing:
- Generated 10 new worlds, waited stationary at spawn for world generation to finish. => no rogue cubes

**Comment by Barteks2x** [comment]
did you also try flying around for a while? (don't teleporrt/change render distance, these may be  broken in other places)

**Comment by Cyclonit** [comment]
Further testing:
- Using the previously generated worlds, teleported outside of the spawn area and waited stationary for world generation to finish => no rogue cubes

**Comment by Barteks2x** [comment]
Does it mean that the PR is ready to merge?

**Comment by Cyclonit** [comment]
Not yet, I am still suspicious and dont want to break your master again. This bugs me a lot... I'll continue working on this after work ~8h from now.

**Comment by Barteks2x** [comment]
I will test it myself too, I'm waiting for this PR to do some internal changes to the way GeneratorPipeline works (ie. generate cubes close to player first) and to CubeCache classes (started in the new branch). I didn't want do it yet to avoid some awful merge conflicts. It should also fix #12.

**Comment by Barteks2x** [comment]
It looks like cubes it doesn't unload some cubes. They eventually do get unloaded when vanilla forces unloading all cubes that are not kept loaded by any player, but these are my testing results:

After /tp 10000 ~ 10000 and then /tp ~ ~ ~100:
![after-tp](https://dl.dropboxusercontent.com/u/54602353/after-tp.png)

And after waiting a while (vanilla adds these cubes to unload queue):
![after-wait](https://dl.dropboxusercontent.com/u/54602353/after-waiting.png)

**Comment by Cyclonit** [comment]
Those cubes are not the problem, as they are accounted for by the CubeCache. The cubes this issue refers to remain in DependencyManager.requiredMap and are no longer present in the CubeCache.

**Comment by Barteks2x** [comment]
They are not this specific problem, but they are still a problem. The only reason it "works" is because every time vanilla saves all chunks, it goes over all Columns (Chunks) from ChunkProviderServer and checks if there is an entry for it in PlayerChunkMap, and if there isn't - the chunk is unloaded.

**Comment by Cyclonit** [comment]
After some further testing I encountered this bug again. I moved around at first, teleport far away, such that all previously loaded cubes should be unloaded. In the end 51 dependent cubes did not advance further and 1475 requirements were unresolved.

**Comment by Cyclonit** [comment]
Resolved in #18 commit 871adbe.
