### ISSUE TITLE
Crash with Extra Utilities

### ISSUE THREAD

**Issue by BaccarWozat** [Barteks2x/CubicChunks#210]
Using Forge 2309, CC 0.0.600.0 and Extra Utilities 1.4.2. Everything loads and apparently generates as normal, but from the ESC menu when I click on Options or Mod Options it crashes.

EDIT: I ran it again and it wasn't waiting for me to click on options, but rather just happens seconds after the map loads.

Crash log: https://pastebin.com/SY5TjSDY
FML Client Latest: https://www.dropbox.com/s/7wo6ure9g7sj1lw/fml-client-latest.log?dl=0

EDIT 2: Just tried it with Extra utilities 1.4.3 and still crashes after a few seconds.

Crash log: https://pastebin.com/G4n0jVd5
FML Client Latest: https://pastebin.com/GT9ukDyq

**Comment by Niko-sk2x** [comment]
It's already fixed in the latest build.
