### ISSUE TITLE
Crash with Forge 2314

### ISSUE THREAD

**Issue by BaccarWozat** [Barteks2x/CubicChunks#211]
It actually doesn't get as _far_ as a crash log here. Forge 2309 still works so I'm reverting to that.

Minecraft log: https://pastebin.com/WXf5xqru
FML-client-latest.log: https://pastebin.com/ftBi1Dgc

**Comment by Niko-sk2x** [comment]
Ah, that's... surprising.

A forge pull request **that I made** broke it. It's easy to fix, but mixin is being a bit stupid here.
