### ISSUE TITLE
Chorus fruit doesn't grow at Y>255

### ISSUE THREAD

**Issue by BaccarWozat** [Barteks2x/CubicChunks#217]
Don't know if this is overworld-only, but I doubt it. It did grow at Y=230 on the same map.

![2017-06-08_23 32 26](https://user-images.githubusercontent.com/8357501/26961421-0e0b0260-4ca4-11e7-8e7c-bf4328a3d1f9.png)

**Comment by ghost** [comment]
Probaly the same thing as no ores below y0

**Comment by Niko-sk2x** [comment]
Ores below y=0 do generate in CustomCubic world type.

I simply didn't remove height limit from chorus.

**Comment by ghost** [comment]
If there are generating on custom cubic why it does not generate on vanillacubic? Isn't it just a copy paste code?

**Comment by Niko-sk2x** [comment]
VanillaCubic isn't even coypasted. I just directly use vanilla generator, which obviously only knows about 0-256, and fill everything below with stone.

**Comment by Niko-sk2x** [comment]
Closing as this is part of #152
