### ISSUE TITLE
CubicChunks crash with ic2

### ISSUE THREAD

**Issue by ghost** [Barteks2x/CubicChunks#218]
With only ic2 and cubicchunks installed, I cannot even create a new world. It just crashes. If a create a world without ic2 and enter the world with ic2, I see flying blocks everywhere. When I enter the world the second time, it crashes.

**Comment by Niko-sk2x** [comment]
Flying blocks everyehwre? That looks a lot like IC2 attempting to use `ExtendedBlockStorage`

**Comment by ModForge** [comment]
So what can I do?

**Comment by Niko-sk2x** [comment]
Wait for me to see what actually causes it. Probably nothing else you can do.

**Comment by Niko-sk2x** [comment]
It works for me. No idea what is your problem. Provide crash log and which version you are using.

**Comment by Niko-sk2x** [comment]
There are still some (unlikely to be fixed) issues with IC2, but the crash is fixed.
