### ISSUE TITLE
Move away from using ICubicWorld as replacement of World in cubic chunks code

### ISSUE THREAD

**Issue by Niko-sk2x** [Barteks2x/CubicChunks#221]
Instead, use World, and cast to ICubicWorld when needed.

It wasn't really a good decision to do it that way. It provides little simplification while making it hard to use methods in World that aren't already there in `ICubicWorld`, and makes updates harder. Same should go for `IColumn`

**Comment by Cyclonit** [comment]
Do you want it to be cast on every use or are stored casted references okay?

**Comment by Niko-sk2x** [comment]
It really depends on what and where is used more frequently. If a class nearly exclusively uses ICubicWorld methods - storing ICubicWorld is ok. If a method uses ICubicWorld methods a lot - storing it i  lical variable would be ok.
