### ISSUE TITLE
Exception after player connected to dedicated Forge server with Cubic Chunks.

### ISSUE THREAD

**Issue by Foghrye4** [Barteks2x/CubicChunks#223]
A several exceptions catched after player successfully connect to dedicated Forge server with Cubic Chunks build 616 (MC1.11). Server works fine and ban player for floating too much. At player side no chunks rendered. Only sky and clouds.
[Client side log](https://github.com/OpenCubicChunks/CubicChunks/files/1067975/log.txt)
[FML Server log](https://github.com/OpenCubicChunks/CubicChunks/files/1067990/fml-server-latest.txt)

**Comment by Niko-sk2x** [comment]
You need to set world type in `server.properties` to `CustomCubic` or `VanillaCubic`

**Comment by Niko-sk2x** [comment]
I was wrong, sorry, turns out this is the cause:
`[14:39:18] [Server thread/INFO] [cubicchunks/]: Skipping world net.minecraft.world.WorldServer@3d899a82 with type cubicchunks.world.type.CustomCubicWorldType@21352fa2 due to potential compatibility issues`

**Comment by Foghrye4** [comment]
So I'm looking at a code and could not understand where you set that Predicate...
Nevermind. Found it. But still I don't get it why its working without annotation such as ```@SidedProxy(clientSide = "cubicchunks.CommonEventHandler.ClientProxy", serverSide = "cubicchunks.CommonEventHandler.ServerProxy")```

**Comment by Niko-sk2x** [comment]
It's a special forge thing - a proxy. A it's set reflectively by forge depending on the the server/client size - if it's dedicated server is use server proxy, if it's client - it uses client proxy, look at `@SidedProxy` javadoc.

**Comment by Foghrye4** [comment]
After #225 fix compiled versions of server shut itself down after player connected due to abnormal long tick. Player successfully receive chunks and entity data and able to walk and look around but it seems that server is not ticking.
Crash reports and logs:
[crash-2017-06-17_15.19.32-server.txt](https://github.com/OpenCubicChunks/CubicChunks/files/1082548/crash-2017-06-17_15.19.32-server.txt)
[crash-2017-06-17_15.49.30-server.txt](https://github.com/OpenCubicChunks/CubicChunks/files/1082549/crash-2017-06-17_15.49.30-server.txt)
[fml-server-3.txt](https://github.com/OpenCubicChunks/CubicChunks/files/1082551/fml-server-3.txt)
[fml-server-latest.txt](https://github.com/OpenCubicChunks/CubicChunks/files/1082550/fml-server-latest.txt)

EDIT:
It's just a performance issue. After I have raised max tick length in server properties I was able to launch server normally. Almost normally. This issue should be closed after #225 will be merged.

**Comment by Niko-sk2x** [comment]
Closed with #225
