### ISSUE TITLE
Tree generation glitches

### ISSUE THREAD

**Issue by BaccarWozat** [Barteks2x/CubicChunks#236]
Using build 625, Forge 2315 and MalisisCore 5.2.1. Both worlds were seed 1 customcubic with all octaves set to 1 and the lower four factors (depth noise and lower) set to 1024.

This seems to be different for different worlds and mod combinations. On the first world I noticed some spruce trees stopped generating at Y=256, but many which started as low as Y=254 grew above that limit with no problem.
![2017-06-20_22 14 03](https://user-images.githubusercontent.com/8357501/27366382-777498c2-560b-11e7-8f0d-a39ca6e63d32.png)

This was confirmed to also be the case with jungle trees, though as you can see in the background it is not universally prevalent, and about a chunk higher they resumed their appearance.
![2017-06-20_22 28 05](https://user-images.githubusercontent.com/8357501/27366418-a1a6d45c-560b-11e7-8a02-f228a6c5087c.png)

Attempts to replicate this by mass growing spruce trees were unfruitful, so it is a generation issue:
![2017-06-20_22 29 16](https://user-images.githubusercontent.com/8357501/27366444-bca14652-560b-11e7-89f4-dd806998226d.png)

I started a new world, but it was entirely different. Some trees generated leaves but no logs.
![2017-06-20_22 46 05](https://user-images.githubusercontent.com/8357501/27366469-f1aa5e42-560b-11e7-90f4-975a02b64715.png)

Other trees had their sides missing. This used to mean the chunk did not generate all its blocks correctly and you could bump up against the phantom tree leaves, but here they are completely missing.
![2017-06-20_22 46 18](https://user-images.githubusercontent.com/8357501/27366496-1f8e569c-560c-11e7-984f-287c882b10d3.png)

The problem height on this world was 224 instead of 256, and it behaved the same.
![2017-06-20_22 49 18](https://user-images.githubusercontent.com/8357501/27366530-57232592-560c-11e7-9b63-4d9147d56715.png)

I didn't get a picture in time, but in the first world there were a number of random floating stone blocks like static in one area, but when I approached them they vanished.

**Comment by BaccarWozat** [comment]
After further testing and looking around the world, I've concluded it isn't about specific limits, but just some chunks not generating tree elements. Could probably be anywhere in the world.

**Comment by ghost** [comment]
Maybe the trees could wait to generate until the rest of the chunks that would contain the tree have loaded.

Where in the code are the trees generated?

**Comment by Niko-sk2x** [comment]
Except that I can't reproduce the issue. It works fine for me.

Trees are generated here:  https://github.com/OpenCubicChunks/CubicChunks/blob/f2a423a4e79788447eb883ea6522f411d8661ea4/src/main/java/cubicchunks/worldgen/generator/custom/populator/DefaultDecorator.java#L123-L133 using modified vanilla generators, with these mixins:
https://github.com/OpenCubicChunks/CubicChunks/tree/f2a423a4e79788447eb883ea6522f411d8661ea4/src/main/java/cubicchunks/asm/mixin/fixes/common/worldgen/tree.

Could you record it from the moment you create the world to where you find such treee? Maybe find a seed and settings where it consistently happens?

**Comment by BaccarWozat** [comment]
I think it's completely random and therefore irreproducible consistently. The other day someone posted a chunk error where the chunk generated air instead of stone and mushrooms/snow spawned on it. But restarting the world gave the full chunk.

**Comment by Niko-sk2x** [comment]
It works fine on 2 of my computers. All I can do is speculate about the cause. I can create a modified cubic chunks version with an awfully huge amount of logging, which should help tracking it down.

**Comment by ghost** [comment]
It happened to me, too.

**Comment by Niko-sk2x** [comment]
Apparently it happens to everyone except me.

**Comment by Niko-sk2x** [comment]
I was able to reproduce it for a single chunk in vanilla cubic once. It affected the whole vanilla seized chunk and, what i find unexplainable, the opacity index/server height map had values as if the blocks have been generated. I will try to find a screenshot of it. I was unable to reproduce it again.

**Comment by Setadokalo** [comment]
Ghost-Blocks, Premium Edition

**Comment by Niko-sk2x** [comment]
I didn't get this bug for a long time, so it's probably gone. Create new issue if it happens again.
