### ISSUE TITLE
(CustomCubic) Ugly plateaus form in the Vanilla Cubic world type

### ISSUE THREAD

**Issue by ghost** [Barteks2x/CubicChunks#239]
![2017-06-28_13 52 04](https://user-images.githubusercontent.com/29759683/27652267-1a7756c4-5c09-11e7-856f-64647791ffa8.png)

**Comment by Niko-sk2x** [comment]
It seems like I made it just cut off the terrain at y=128. Should be easy to fix.

**Comment by ghost** [comment]
Thank you!
(Can you not cut it off at all or at least add an option for that? Some may want extremely tall mountains.)

**Comment by Niko-sk2x** [comment]
VanillaCubic literally calls vanilla world generator. There is no way for it to go above y=256.
CustomCubic with customized configuration needs to be used for real cubic chunks generator.

**Comment by BaccarWozat** [comment]
Amplified mapgen sometimes goes to 256 and forms plateaus (you can see this in both vanilla and Biomes O'Plenty amplification). The behavior in CC of such maps would be the same. The real heights are in CustomCubic as Barteks said.
