### ISSUE TITLE
Flat worlds: Normal biomes still spawning

### ISSUE THREAD

**Issue by ghost** [Barteks2x/CubicChunks#240]
![2017-06-29_15 31 09](https://user-images.githubusercontent.com/29759683/27706565-012826b2-5ce0-11e7-95e8-4b00346398f5.png)

**Comment by Cyclonit** [comment]
I cannot reproduce this with the most recent versions.

**Comment by Niko-sk2x** [comment]
I can still reproduce it.

**Comment by Niko-sk2x** [comment]
Fixed in https://github.com/OpenCubicChunks/CubicWorldGen/commit/53d8e4e92f7dc156c2b4183ff8d0be0208bcd37d
