### ISSUE TITLE
Placing two lily pads next to each other below y = 0 or above y = 255 breaks one of them and may dupe it

### ISSUE THREAD

**Issue by bluebear94** [Barteks2x/CubicChunks#241]
To reproduce:

literally place two lily pads next to each other

**Comment by Niko-sk2x** [comment]
Are you sure it's actually a cubic chunks issue?

**Comment by bluebear94** [comment]
It doesn't happen in vanilla.

**Comment by Niko-sk2x** [comment]
This is strange because I don't think I'm modifying any lilypad-related code.

**Comment by bluebear94** [comment]
Confirmed that this bug occurs only outside the 0 – 255 range.
