### ISSUE TITLE
FoamFix 0.7.1 crashes CC

### ISSUE THREAD

**Issue by BaccarWozat** [Barteks2x/CubicChunks#242]
With Forge 2315 and CC 625. Did not get as far as a crash log.

Minecraft log: https://pastebin.com/VFjih7eL
FML-client-latest.log: https://pastebin.com/mLGXpri4

**Comment by Niko-sk2x** [comment]
This looks like another instance of https://github.com/SpongePowered/Mixin/issues/189, I just need to update mixin.

**Comment by Foghrye4** [comment]
Oh My Satan lord! @Barteks2x! You are alive!

**Comment by Niko-sk2x** [comment]
@Foghrye4 I will explain everything on discord, once I install it.
