### ISSUE TITLE
A Farlands Option

### ISSUE THREAD

**Issue by MatthewTNT79** [Barteks2x/CubicChunks#247]
In the custom cubic menu, there could an option for generating the farlands. The menu would be on its own separate page and will simply have checkboxes for generating the farlands at all, or in the x, y, or z axes.

**Comment by sirsavary** [comment]
Farlands preset could be neat. You mean all messed up before they fixed the bug, right?

**Comment by Niko-sk2x** [comment]
Configuring it for separate axis isn't going to happen. But there will be option to choose a noise generator that has that issue unfixed.

**Comment by FyreByrns** [comment]
Is there not a modified jar that does generate farlands?

**Comment by Niko-sk2x** [comment]
There is but it requires using that modified jar.

**Comment by FyreByrns** [comment]
Would there be a way to integrate that modded jar into the regular jar and simply have a checkbox to select or deselect farlands? That's pretty much the only way I see to make it any easier.

**Comment by Niko-sk2x** [comment]
Fixed in https://github.com/OpenCubicChunks/CubicWorldGen/commit/c511846a48e9528dac0aebd6a4e85e522b3d771e
