### ISSUE TITLE
Cube in column not the same as stored cube!

### ISSUE THREAD

**Issue by RelativeProgramming** [Barteks2x/CubicChunks#251]
While flying around in a custom Cubic World, the game crashes sometimes with this exception:

[latest.txt](https://github.com/OpenCubicChunks/CubicChunks/files/1150507/latest.txt)

**Comment by Niko-sk2x** [comment]
Duplicate of #250

**Comment by Niko-sk2x** [comment]
Working on it right now, it's tricky to figure out what actually causes it so it may take a while.
