### ISSUE TITLE
Organize Dependents in RequiredCube according to the stages they require

### ISSUE THREAD

**Issue by Cyclonit** [Barteks2x/CubicChunks#26]
Currently, RequiredCube stores all Dependents in a single collection. Whenever its wrapped cube advances a stage all Dependents receive the update, regardless of whether they actually need it. If RequiredCube had individual Collections per GeneratorStage the amount of unnecessary updates could be reduced.

**Comment by Barteks2x** [comment]
The way it currently works is still way faster than what it was before, so I would consider it low priority for now.

**Comment by Cyclonit** [comment]
I agree, just an idea for the future.

**Comment by Barteks2x** [comment]
This may be actually needed, VanillaCubic is very slow when using the depenndency system (or some other optimizations may be needed).

It becomes slow because for vanilla height range, each cube depends on every other cube. And for lighting each cube depends on `CubeCoords(x - 2, -2, z - 2)` to `CubeCoords(x + 2, 15 + 2, z + 2)`.

**Comment by Cyclonit** [comment]
I might take a shot at this over the weekend, but somehow any attempt of generating a new world with any current branch fails due to a casting error. Once I figure that out I'll try solving this.

**Comment by Barteks2x** [comment]
Are you sure you have this commandline argument: `-Dfml.coreMods.load=cubicchunks.asm.CoreModLoadingPlugin`?

**Comment by Cyclonit** [comment]
I was able to run the game by just using "gradlew runClient" without changing any JVM arguments. It just worked out of the box. Now, I get this [gradle.log.txt](https://github.com/Barteks2x/CubicChunks/files/321645/gradle.log.txt) when trying to use runClient. Running it from inside IDEA didn't work in general (same error) and adding the VM argument to the configuration doesn't fix it.

**Comment by Barteks2x** [comment]
I totally forgot about it. As of some recent version, specifying Mixin compatibility level from CoreModLoadingPlugin is deprecated, and manifest entry should be used instead. For dev environment manifest file isn't loaded, so you need this commandline option: 
```
-Dmixin.env.compatLevel=JAVA_8
```
I will add it to readme.txt.

**Comment by Cyclonit** [comment]
Thank you very much, now everything works as it should again.

**Comment by Cyclonit** [comment]
This change causes a significant decrease in performance. The cost of initialization and use of the additional structures outweigh any potential benefits. In my tests (generating 10 worlds with each system), the current layout reached an average of 693.7 cubes/s, the proposed layout merely 439 cubes/s.

**Comment by Barteks2x** [comment]
You can try to use visualvm sampler to see what causes performance issues.
