### ISSUE TITLE
No Cubic Chunk Borders Below Y 0-255

### ISSUE THREAD

**Issue by Technoturnovers** [Barteks2x/CubicChunks#265]
In vanilla, if you press F3 + G, you get chunk borders that extend all the way to the world top and bottom. This behavior is not changed in vanilla, meaning it doesnt show the borders below the vanilla world height bounds and the chunks shown arent cubic and don't show the cubic chunk bottoms.
![2017-07-25_14 34 27](https://user-images.githubusercontent.com/19103643/28587780-5634997c-7146-11e7-95ff-0f9bfac881a7.png)

**Comment by Niko-sk2x** [comment]
Fixed in PR #308
