### ISSUE TITLE
Issues with Cavern mod

### ISSUE THREAD

**Issue by Niko-sk2x** [Barteks2x/CubicChunks#267]
https://github.com/kegare/Cavern/issues/27

**Comment by Kevadroz** [comment]
The world loads the same amount of times without Cavern, but it use the normal amount of memory: arround 700M. I that Cubic Chunks loads the world a number of times before load sucefully, another issue.

**Comment by Niko-sk2x** [comment]
Currently cubic chunks has higher memory usage than vanilla. If cavern forces all of it's dimensions to be kept loaded, then this mod probably is doing it wrong.
