### ISSUE TITLE
Hostile mobs spawn at high light levels in Y>2048

### ISSUE THREAD

**Issue by BaccarWozat** [Barteks2x/CubicChunks#272]
There I was, 29km in the air, putting torches everywhere on a floating island. I have More Overlays installed so I can tell that it is properly lit up. I saw a bunch of hostile mobs (skeletons, creepers, zombies etc.) and had not seen them there before. I set it to Peaceful mode, waited for them to vanish, then back to Normal mode and they started appearing on the other side of the island (also well lit).

I will try and see if it happens with all extraneous mods removed.

![2017-08-15_04 09 52](https://user-images.githubusercontent.com/8357501/29309552-cb7d805c-816f-11e7-85da-1605630f1260.png)

**Comment by Niko-sk2x** [comment]
This is strange. Did it happen in earlier versions?

**Comment by BaccarWozat** [comment]
Update: I removed all extraneous mods, set to peaceful, went to Y=2570, spawned a 101x101 platform, placed torches and set to normal/night. Moved away from center and BAM, mobs! I'm using build 298 and have no idea if it's in earlier versions as well.

![2017-08-15_05 03 12](https://user-images.githubusercontent.com/8357501/29311372-5fb7ee36-8177-11e7-9bb9-8879c5aa09f5.png)
