### ISSUE TITLE
1.12.1 Crashes when trying to load mod in forge server

### ISSUE THREAD

**Issue by andrewathalye** [Barteks2x/CubicChunks#275]
Whenever I try to use the compiled mod with forge server 1.12.1 (using latest codebase)
the server crashes shortly after startup due to ClassNotFoundException regarding GuiEvent.
I was able to fix this by editing ClientEventHandler.java, and the produced jar was able to
successfully load.
[CubicChunks-1.12.1-0.0.710.0.zip](https://github.com/OpenCubicChunks/CubicChunks/files/1265333/CubicChunks-1.12.1-0.0.710.0.zip)
Attatched is the working build with modified ClientEventHandler

**Comment by Setadokalo** [comment]
Um... If you made a modification to the class that makes it work, why not format that as a pull request rather than as an issue?

**Comment by andrewathalye** [comment]
Sorry, but I'm a noob to Git and don't really know how to make a pull request.
How exactly would I go about it?
I'll try and figure it out myself, but if I don't, it would be nice if you could give me a clue.

**Comment by andrewathalye** [comment]
I figured out how to do a pull request.
I'll close the issue now! Sorry about that.
