### ISSUE TITLE
Discord invite invalid or expired

### ISSUE THREAD

**Issue by DaMatrix** [Barteks2x/CubicChunks#302]
Title, I'm not able to join. Thanks!

**Comment by Niko-sk2x** [comment]
Is it this link that is expired? https://discord.gg/kMfWg9m

**Comment by DaMatrix** [comment]
yup, that one

**Comment by Niko-sk2x** [comment]
Use this one for now, I will fix it later https://discord.gg/neqDQha

**Comment by DaMatrix** [comment]
new one:

![image](https://user-images.githubusercontent.com/11216106/31793760-7296ce64-b520-11e7-9e37-b39faa3500b9.png)

**Comment by Niko-sk2x** [comment]
I copied it straight from discord. Blame discord.

**Comment by Niko-sk2x** [comment]
As a last attempt, here is another one, but this one will expire after some time https://discord.gg/yGX4N

**Comment by DaMatrix** [comment]
wierd, using the join server button IN discord worked. thanks!
