### ISSUE TITLE
Very low FPS near Oceans {fast collision checking actually very slow}

### ISSUE THREAD

**Issue by XBagon** [Barteks2x/CubicChunks#311]
Deeper oceans -> lower fps

**Comment by DaMatrix** [comment]
Literally has NOTHING to do with cubic chunks, just Minecraft in general. You can use optifine to disable water animations, should fix it.

**Comment by AlexGreason** [comment]
Generated a world with 50+ km deep oceans to test, results:

Spawned in water, shaders on, water animations/particles on, 20-40 fps, but noted that the particles in the water were moving strangely, with long pauses and big, jerky movements
shaders off, water animations/particles on, no change
shaders on, water animations off, particles on, no change
shaders on, water animations off, water particles off, 60 fps (but with drops down to exactly 30 until I start moving again, then goes back to exactly 60).
shaders on, water animations on, water particles off, 45-55ish
(all results with horizontal render distance of 16, vertical render distance of 10)

Edit: upon turning particles back on after testing, fps dropped to 1. After ten seconds or so recovered to about 10 fps.

EditEdit: It's definitely the particles specifically. particles set to minimal, all is well. Set to all, 10 fps at best. Turned shaders off, 30 fps with particles, turned particles to minimal 60 fps, turned particles back on, 40 ish.... very inconsistent, seems to only sometimes cause the lag.

EditEditEdit:
So I've now been in the states of:
shaders, particles, good fps
shaders, particles, terrible fps
shaders, no particles, good fps
no shaders, particles, good fps
no shaders, no particles, good fps
not yet observed:
bad fps without shaders, bad fps without particles

**Comment by DaMatrix** [comment]
Try it in vanilla with a superflat world with a 256 deep ocean

**Comment by AlexGreason** [comment]
vanilla, superflat, water from bedrock to top, no shaders:
Fps just fine even at large render distance, water particles exhibiting same behaviour.
Can't say anything about changes with particles set to minimal (besides confirming that that lets you turn them off in vanilla) since minecraft on my computer never goes above 60 fps regardless of what I do with vsync or max framerate or settings, and I get 60 with and without particles regardless of render distance in that world.

**Comment by Niko-sk2x** [comment]
Unrelated: Your 60FPS limit is most likely GPU drivers settings.

**Comment by Niko-sk2x** [comment]
@Foghrye4 this has been confirmed to be an issue with fast collisions checks. Reverting it to slow collisions checks fixes the issue. Since you implemented it (iirc) you fix it.

**Comment by Foghrye4** [comment]
May I remove "fast" collision check completely instead?

**Comment by Niko-sk2x** [comment]
If you can't fix that - yes.

**Comment by Foghrye4** [comment]
I can, I'm just lazy and I see no point to do it. I think its just because overwritten method is faster than injection.

**Comment by Niko-sk2x** [comment]
You can verify that by injecting a copy of the "slow" (vanilla-style) one
