### ISSUE TITLE
Crash on select Customize in CustomCubic world type

### ISSUE THREAD

**Issue by BaccarWozat** [Barteks2x/CubicChunks#324]
CC build 786. Forge 2555. MalisisCore 6.3.0

Duplicated another user's (CaptainKyros) sudden crash under the same thing-- creating a new world, selecting CustomCubic and clicking on Customize.

Crash log: https://pastebin.com/GTrZh72J
fml-client-latest.log: 
[fml-client-latest.log](https://github.com/OpenCubicChunks/CubicChunks/files/1569765/fml-client-latest.log)

**Comment by Niko-sk2x** [comment]
Downgrade MalisisCore for now.

**Comment by Niko-sk2x** [comment]
Already fixed.
