### ISSUE TITLE
Activating a projector from the G.L.A.S.S mod crashes when using alongside a Cubic Chunks enabled world

### ISSUE THREAD

**Issue by steampunko** [Barteks2x/CubicChunks#327]
[crash report](https://gist.github.com/steampunko/7b0547dba438406414789a5d10b4b1f2)

**Comment by TheTrueForce** [comment]
It might be an idea to drop your log into a gist(gist.gihub.com) to make your post less of an eyesore.

**Comment by Niko-sk2x** [comment]
GLASS mod won't work.

**Comment by steampunko** [comment]
Why not? Sorry if my asking sounds arrogant, I have no experience with coding.
I also made the log seperate

**Comment by Niko-sk2x** [comment]
It copy-pastes and modifies the `RenderGlobal` class, and overrides a bunch of methods with it's own versions. And then uses that `RenderGlobal` to do it's rendering. Unfortunately his modified version doesn't have cubic chunks patches so it's not going to work.

**Comment by Dushess** [comment]
So, we need to tell about this to mod author...

**Comment by Niko-sk2x** [comment]
I did. He didn't do a coremod which would be a better solution "because coremods are bad" and he doesn't really have time to work on it now.

**Comment by Niko-sk2x** [comment]
Moved to compatibility reports.
