### ISSUE TITLE
Game Crashes on Startup (Linux Mint)

### ISSUE THREAD

**Issue by TheHypeTrain** [Barteks2x/CubicChunks#330]
The game crashes on startup. I CDd to the folder with the gradlew file (in my mods folder) and cloned the repository. I ran the commands like the README file said ( $ ./gradlew setupDevWorkspace and $ ./gradlew build). I set up IntelliJ IDEA, is this necessary? The game crashes when trying to construct the mods. Here is the crash report:
[crash-2018-01-10_17.03.58-client.txt](https://github.com/OpenCubicChunks/CubicChunks/files/1620603/crash-2018-01-10_17.03.58-client.txt)

**Comment by Niko-sk2x** [comment]
I have no idea how you managed to make it crash that way. The mod jar is incomplete in a very weird way. Also you didn't clone the git repository. And setting up idea is not necessary if you just want the mod jar. 

And this is not a place for support. Join my discord for this.

**Comment by TheHypeTrain** [comment]
Thanks for your time. I think I've solved the problem, I'll make sure to report in the correct place next time.

**Comment by Niko-sk2x** [comment]
This is the right place to report actua bugs. Most of the "crash at startup" are not bugs.
