### ISSUE TITLE
Extra Utilities 2 Support: Quantum Quarry crashes game

### ISSUE THREAD

**Issue by dunnousername** [Barteks2x/CubicChunks#331]
I thought I'd add this here. I'm not sure if other mods try to generate chunks for a world that doesn't exist, but it might be worth nothing:
https://pastebin.com/RJ3Jtz7N
Extra Utilities 2, version 1.12-1.7.2 from CurseForge.
MalisisCore 6.3.0.
CubicChunks 809 (compiled from git on Wed 17 Jan 2018).
Again, I'm not sure how relevant it is, but I'm not sure how many other mods implement a "miner" that grabs ores from another dim (if that is the problem).
I can confirm that the same versions work if CubicChunks is disabled.

Edit Thu 18 Jan 2018: I used the upload log function in MultiMC to get another log: https://paste.ee/p/sLLZn
This one happens at y 69, not below y = 0.
Also, note that an RF source must be used to start the quarry; I used the infinite one from EU2

**Comment by Laserzwei** [comment]
> Block location: World: (-238,-4,232)

& the crash occuring in Extra utlities code:
I'm pretty sure that Extra utilities is to blame, since it's not expecting to have a quarry  y<0

**Comment by dunnousername** [comment]
It also occurs at normal height (tested again, must have uploaded wrong crash log)

**Comment by Laserzwei** [comment]
You should upload that crash-log then

**Comment by ghost** [comment]
Apologies to interject but just in case you're not notified when another person edits a message, the original message was modified with the other crash log for normal-height quarrying:

![image](https://user-images.githubusercontent.com/24266948/35258152-b6935642-0051-11e8-8e67-c9361ca139a4.png)

Sorry if you've already seen it, just trying to be of help! :)

**Comment by Niko-sk2x** [comment]
Is this still the case?

**Comment by Niko-sk2x** [comment]
Closing for now. If it's still an issue, report to compatibility reports page.
