### ISSUE TITLE
Chunkloaders don't work

### ISSUE THREAD

**Issue by Laserzwei** [Barteks2x/CubicChunks#332]
Since the way chunks are created/saved etc. changed, chunkloaders don't work (properly?).
I tested it with chickenchunks and it creates chunkloader tickets, but the chunks aren't loaded. But no crashes either- that's good, isn't it?
This might be because the game (ticket-system, viewable via /chunkloaders in Chickenchunks) doesn't know which chunks on the y-axis to load?
Naively I would suggest loading the chunks above and below the chunkloader. Obviously not all of them! +/-8 would be vanilla (more or less) behavior or simply only the one CubicChunk where the loader is placed. 
I've got no idea how hard it would be to implement this :/

**Comment by dunnousername** [comment]
Does it work with a cubicchunks save format (but normal height still, 0<y<255)? It may never load less than 0 with chicken chunks, but how about at, say, 64? And, are cubes chunkloaded individually?

**Comment by Laserzwei** [comment]
In its current state Chickenchunks doesn't keep any chunks loaded. I just noticed that forge's ticket system registered the request to keep chunks loaded (/chunkloaders showed it). I tested it in the 0<y<255 range as well and it doesn't work there either. 

> Are cubes chunkloaded individually?

I choose to do the testing in the same x and z Coordinates, so only the 3 ranges "y in [-inf,0), [0,255], (255,inf]" could have an effect. Sadly no chunk outside if my character was loaded.

Tested via Minecarts passing a detector rail next to command block.

**Comment by dunnousername** [comment]
Aha - apparently this is a known issue (unless it was just added). If you go to the wiki compatibility list (https://github.com/OpenCubicChunks/CubicChunks/wiki/Compatibility-list) you can see it mentioned as "not working". I ran a quick search and couldn't find any other chunk loading mod. (EU2 has a chunk loading block, whatever that does, but EU2 doesn't seem to like CC)

**Comment by Laserzwei** [comment]
I added that entry :)
Edit: Ftb utilities contains a chunkloading mechanic, but it seems to be broken in 1.12. Therefore I didn't test it with Cubic Chunks

**Comment by CursedFlames** [comment]
I've made a cubic chunkloader mod, it's still alpha and it's not on github yet but the download is pinned in #general on the CC discord.

**Comment by Niko-sk2x** [comment]
Mostly fixed. Many chunk loading mods still don't work correctly but it probably can be fixed. FtbUtils works. If there are issues with specific mods, report them separately now.
