### ISSUE TITLE
Crash when selecting block for custom ore

### ISSUE THREAD

**Issue by BaccarWozat** [Barteks2x/CubicChunks#333]
CC Build 809, MalisisCore 6.3.2, Forge 2555.
I also had several mods (the Mental Block modpack but with some updates) that added other blocks.
Near the top of the custom ore selection screen were all the vanilla blocks, but as I scrolled towards the bottom of the screen it crashed suddenly.
This happened before to someone else, and I thought it might have been caused by an animated block from Chisel. I can only speculate.
Crashlog: https://pastebin.com/6XYa41Lv
Latest.log: https://pastebin.com/XeqgST1b
Fml-client-latest.log: [fml-client-latest.log](https://github.com/OpenCubicChunks/CubicChunks/files/1649430/fml-client-latest.log)
Screenshot: One click of the mousewheel below this is where the crash happened.
![2018-01-20_19 04 27](https://user-images.githubusercontent.com/8357501/35189640-e99d8e7a-fe14-11e7-9412-736971fa94ed.png)

**Comment by BaccarWozat** [comment]
Update: Having removed and added mods for a while, I discovered that the culprit is [ArchitectureCraft](https://minecraft.curseforge.com/projects/architecturecraft-elytradev). Without it there is no crash.

**Comment by Niko-sk2x** [comment]
I think this is already worked around.
