### ISSUE TITLE
Crash when trying to create a "Custom Cubic"

### ISSUE THREAD

**Issue by Hardfg5000** [Barteks2x/CubicChunks#341]
When I try click the button for customising the custom cubic, the game instantly crashes (got antvenom's far lands mod on it). 

Time: 1/26/18 11:03 PM
--
23:03:58 | game | Description: Updating screen events
23:03:58 | game |  
23:03:58 | game | java.lang.NoClassDefFoundError: jline/internal/Preconditions
23:03:58 | game | at cubicchunks.worldgen.gui.component.UISplitLayout.setSizeOf(UISplitLayout.java:107)
23:03:58 | game | at cubicchunks.worldgen.gui.OreSettingsTab$UIStandardOreOptions.<init>(OreSettingsTab.java:182)
23:03:58 | game | at cubicchunks.worldgen.gui.OreSettingsTab.<init>(OreSettingsTab.java:88)
23:03:58 | game | at cubicchunks.worldgen.gui.CustomCubicGui.reinit(CustomCubicGui.java:96)
23:03:58 | game | at cubicchunks.worldgen.gui.CustomCubicGui.construct(CustomCubicGui.java:89)
23:03:58 | game | at net.malisis.core.client.gui.MalisisGui.doConstruct(MalisisGui.java:150)
23:03:58 | game | at net.malisis.core.client.gui.MalisisGui.display(MalisisGui.java:702)
23:03:58 | game | at net.malisis.core.client.gui.MalisisGui.display(MalisisGui.java:691)
23:03:58 | game | at cubicchunks.world.type.CustomCubicWorldType.onCustomizeButton(CustomCubicWorldType.java:102)
23:03:58 | game | at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:317)
23:03:58 | game | at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
23:03:58 | game | at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:416)
23:03:58 | game | at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
23:03:58 | game | at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
23:03:58 | game | at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
23:03:58 | game | at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
23:03:58 | game | at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
23:03:58 | game | at net.minecraft.client.main.Main.main(SourceFile:123)
23:03:58 | game | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:03:58 | game | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:03:58 | game | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:03:58 | game | at java.lang.reflect.Method.invoke(Method.java:483)
23:03:58 | game | at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
23:03:58 | game | at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
23:03:58 | game | Caused by: java.lang.ClassNotFoundException: jline.internal.Preconditions
23:03:58 | game | at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
23:03:58 | game | at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
23:03:58 | game | at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
23:03:58 | game | ... 24 more
23:03:58 | game | Caused by: java.lang.NullPointerException
23:03:58 | game |  
23:03:58 | game |  
23:03:58 | game | A detailed walkthrough of the error, its code path and all known details is as follows:
23:03:58 | game | ---------------------------------------------------------------------------------------
23:03:58 | game |  
23:03:58 | game | -- Head --
23:03:58 | game | Thread: Client thread
23:03:58 | game | Stacktrace:
23:03:58 | game | at cubicchunks.worldgen.gui.component.UISplitLayout.setSizeOf(UISplitLayout.java:107)
23:03:58 | game | at cubicchunks.worldgen.gui.OreSettingsTab$UIStandardOreOptions.<init>(OreSettingsTab.java:182)
23:03:58 | game | at cubicchunks.worldgen.gui.OreSettingsTab.<init>(OreSettingsTab.java:88)
23:03:58 | game | at cubicchunks.worldgen.gui.CustomCubicGui.reinit(CustomCubicGui.java:96)
23:03:58 | game | at cubicchunks.worldgen.gui.CustomCubicGui.construct(CustomCubicGui.java:89)
23:03:58 | game | at net.malisis.core.client.gui.MalisisGui.doConstruct(MalisisGui.java:150)
23:03:58 | game | at net.malisis.core.client.gui.MalisisGui.display(MalisisGui.java:702)
23:03:58 | game | at net.malisis.core.client.gui.MalisisGui.display(MalisisGui.java:691)
23:03:58 | game | at cubicchunks.world.type.CustomCubicWorldType.onCustomizeButton(CustomCubicWorldType.java:102)
23:03:58 | game | at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:317)
23:03:58 | game | at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
23:03:58 | game | at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:416)
23:03:58 | game | at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
23:03:58 | game | at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
23:03:58 | game |  
23:03:58 | game | -- Affected screen --
23:03:58 | game | Details:
23:03:58 | game | Screen name: net.minecraft.client.gui.GuiCreateWorld
23:03:58 | game | Stacktrace:
23:03:58 | game | at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
23:03:58 | game | at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
23:03:58 | game | at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
23:03:58 | game | at net.minecraft.client.main.Main.main(SourceFile:123)
23:03:58 | game | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:03:58 | game | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:03:58 | game | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:03:58 | game | at java.lang.reflect.Method.invoke(Method.java:483)
23:03:58 | game | at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
23:03:58 | game | at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
23:03:58 | game |  
23:03:58 | game | -- System Details --
23:03:58 | game | Details:
23:03:58 | game | Minecraft Version: 1.12.2
23:03:58 | game | Operating System: Windows 10 (amd64) version 10.0
23:03:58 | game | Java Version: 1.8.0_25, Oracle Corporation
23:03:58 | game | Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
23:03:58 | game | Memory: 379411512 bytes (361 MB) / 738197504 bytes (704 MB) up to 1073741824 bytes (1024 MB)
23:03:58 | game | JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
23:03:58 | game | IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
23:03:58 | game | FML: MCP 9.42 Powered by Forge 14.23.1.2555 8 mods loaded, 7 mods active
23:03:58 | game | States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
23:03:58 | game |  
23:03:58 | game | \| State  \| ID                \| Version          \| Source                                                        \| Signature                                \|
23:03:58 | game | \|:------ \|:----------------- \|:---------------- \|:------------------------------------------------------------- \|:---------------------------------------- \|
23:03:58 | game | \| UCHIJA \| minecraft         \| 1.12.2           \| minecraft.jar                                                 \| None                                     \|
23:03:58 | game | \| UCHIJA \| mcp               \| 9.42             \| minecraft.jar                                                 \| None                                     \|
23:03:58 | game | \| UCHIJA \| FML               \| 8.0.99.99        \| forge-1.12.2-14.23.1.2555.jar                                 \| e3c3d50c7c986df74c645c0ac54639741c90a557 \|
23:03:58 | game | \| UCHIJA \| forge             \| 14.23.1.2555     \| forge-1.12.2-14.23.1.2555.jar                                 \| e3c3d50c7c986df74c645c0ac54639741c90a557 \|
23:03:58 | game | \| UCHIJA \| mercurius_updater \| 1.0              \| MercuriusUpdater-1.12.2.jar                                   \| None                                     \|
23:03:58 | game | \| UCHIJA \| malisiscore       \| 1.12.2-6.3.2     \| malisiscore-1.12.2-6.3.2.jar                                  \| None                                     \|
23:03:58 | game | \| UCHIJA \| cubicchunks       \| 1.12.2-0.0.809.0 \| CubicChunks-1.12.2-0.0.809.0-all_bottomVoidFix-instaDeath.jar \| None                                     \|
23:03:58 | game | \| UD     \| cubicchunkscore   \| @@VERSION@@      \| minecraft.jar                                                 \| None                                     \|
23:03:58 | game |  
23:03:58 | game | Loaded coremods (and transformers):
23:03:58 | game | MalisisCorePlugin (malisiscore-1.12.2-6.3.2.jar)
23:03:58 | game |  
23:03:58 | game | CubicChunksCoreMod (CubicChunks-1.12.2-0.0.809.0-all_bottomVoidFix-instaDeath.jar)
23:03:58 | game |  
23:03:58 | game | GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.1010' Renderer: 'AMD Radeon(TM) R7 Graphics'
23:03:58 | game | Launched Version: 1.12.2-forge1.12.2-14.23.1.2555
23:03:58 | game | LWJGL: 2.9.4
23:03:58 | game | OpenGL: AMD Radeon(TM) R7 Graphics GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1010, ATI Technologies Inc.
23:03:58 | game | GL Caps: Using GL 1.3 multitexturing.
23:03:58 | game | Using GL 1.3 texture combiners.
23:03:58 | game | Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
23:03:58 | game | Shaders are available because OpenGL 2.1 is supported.
23:03:58 | game | VBOs are available because OpenGL 1.5 is supported.
23:03:58 | game |  
23:03:58 | game | Using VBOs: Yes
23:03:58 | game | Is Modded: Definitely; Client brand changed to 'fml,forge'
23:03:58 | game | Type: Client (map_client.txt)
23:03:58 | game | Resource Packs: _Minecraft Default Texture Pack 1.12
23:03:58 | game | Current Language: English (US)
23:03:58 | game | Profiler Position: N/A (disabled)
23:03:58 | game | CPU: 4x AMD A10-7800 Radeon R7, 12 Compute Cores 4C+8G
23:03:58 | game | [23:03:58] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Asus\AppData\Roaming\.minecraft\crash-reports\crash-2018-01-26_23.03.58-client.txt

**Comment by Niko-sk2x** [comment]
That looks like wrong import

**Comment by Hardfg5000** [comment]
How could I fix?

**Comment by Hardfg5000** [comment]
How can I fix?

**Comment by Foghrye4** [comment]
Clone repository, use correct import, push commit to your branch and create pull request.

**Comment by Niko-sk2x** [comment]
Already fixed.

**Comment by ghost** [comment]
can some one please explain what you are supposed to do? the instructions are confusing

**Comment by BaccarWozat** [comment]
Install MalisisCore alongside CC, like any Forge mods, and you should be able to access the CustomCubic worldtype. If it doesn't work you might need a later CC or earlier MalisisCore. Later CCs are on the discord.

**Comment by BaccarWozat** [comment]
And you will need CubicWorldGen as well.

**Comment by ghost** [comment]
i have malisis core, cubicworldgen, and cubic chunks. it doesn't crash if malisis isn't installed, but the menu is very difficult to use like that

**Comment by BaccarWozat** [comment]
I'll say it is. The UI _requires_ MalisisCore. It usually crashes or just doesn't load the menus if you don't have it.

**Comment by ghost** [comment]
my apologies for wasting your time. i found the updated files and now it is working perfectly fine

**Comment by ghost** [comment]
Hi, could you share a copy of the updated files? I've tried different Malisis Cores that end with different numbers and they don't work for me. I still crash.

**Comment by Niko-sk2x** [comment]
MalisisCore 6.4.x for MC 1.12.2 should work fine

**Comment by ghost** [comment]
I tried MalisisCore 6.4.1 SNAPSHOT and it didn't work. When I look up Malisis core, it downloads 6.5.1 instead of 6.4.1.

Here's the crash log

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.39.1-SNAPSHOT-all.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.1-SNAPSHOT.jar)
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.970.0-SNAPSHOT-all.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 8/16/19 4:51 PM
Description: Updating screen events

java.lang.NoSuchMethodError: net.malisis.core.client.gui.component.interaction.UITextField.setValidator(Lcom/google/common/base/Predicate;)Lnet/malisis/core/client/gui/component/interaction/UITextField;
	at io.github.opencubicchunks.cubicchunks.cubicgen.common.gui.MalisisGuiUtils.floatInput(MalisisGuiUtils.java:243)
	at io.github.opencubicchunks.cubicchunks.cubicgen.customcubic.gui.AdvancedTerrainShapeTab.<init>(AdvancedTerrainShapeTab.java:125)
	at io.github.opencubicchunks.cubicchunks.cubicgen.customcubic.gui.CustomCubicGui.reinit(CustomCubicGui.java:100)
	at io.github.opencubicchunks.cubicchunks.cubicgen.customcubic.gui.CustomCubicGui.construct(CustomCubicGui.java:92)
	at net.malisis.core.client.gui.MalisisGui.doConstruct(MalisisGui.java:150)
	at net.malisis.core.client.gui.MalisisGui.display(MalisisGui.java:705)
	at net.malisis.core.client.gui.MalisisGui.display(MalisisGui.java:694)
	at io.github.opencubicchunks.cubicchunks.cubicgen.customcubic.CustomCubicWorldType.onCustomizeButton(CustomCubicWorldType.java:104)
	at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:317)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:416)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at io.github.opencubicchunks.cubicchunks.cubicgen.common.gui.MalisisGuiUtils.floatInput(MalisisGuiUtils.java:243)
	at io.github.opencubicchunks.cubicchunks.cubicgen.customcubic.gui.AdvancedTerrainShapeTab.<init>(AdvancedTerrainShapeTab.java:125)
	at io.github.opencubicchunks.cubicchunks.cubicgen.customcubic.gui.CustomCubicGui.reinit(CustomCubicGui.java:100)
	at io.github.opencubicchunks.cubicchunks.cubicgen.customcubic.gui.CustomCubicGui.construct(CustomCubicGui.java:92)
	at net.malisis.core.client.gui.MalisisGui.doConstruct(MalisisGui.java:150)
	at net.malisis.core.client.gui.MalisisGui.display(MalisisGui.java:705)
	at net.malisis.core.client.gui.MalisisGui.display(MalisisGui.java:694)
	at io.github.opencubicchunks.cubicchunks.cubicgen.customcubic.CustomCubicWorldType.onCustomizeButton(CustomCubicWorldType.java:104)
	at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:317)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:416)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiCreateWorld
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1506292800 bytes (1436 MB) / 1967652864 bytes (1876 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 15 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID              | Version                   | Source                                         | Signature                                |
	|:------ |:--------------- |:------------------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft       | 1.12.2                    | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp             | 9.42                      | minecraft.jar                                  | None                                     |
	| LCHIJA | FML             | 8.0.99.99                 | forge-1.12.2-14.23.5.2838.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge           | 14.23.5.2838              | forge-1.12.2-14.23.5.2838.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | better_diving   | 1.3.91                    | BetterDiving-1.12.2-1.3.91.jar                 | None                                     |
	| LCHIJA | bookworm        | 1.12.2-2.2.0              | bookworm - 2.2.0 (1.12.2).jar                  | None                                     |
	| LCHIJA | clearwater      | 1.2                       | clearwater-1.2.jar                             | None                                     |
	| LCHIJA | coralreef       | 2.0                       | CoralReef-2.5-1.12.2.jar                       | None                                     |
	| LCHIJA | cubicchunks     | 1.12.2-0.0.970.0-SNAPSHOT | CubicChunks-1.12.2-0.0.970.0-SNAPSHOT-all.jar  | None                                     |
	| LCHIJA | cubicgen        | 1.12.2-0.0.39.1-SNAPSHOT  | CubicWorldGen-1.12.2-0.0.39.1-SNAPSHOT-all.jar | None                                     |
	| LCHIJA | nhc             | 4.0.3                     | NHCore-1.12-4.0.3.jar                          | None                                     |
	| LCHIJA | dse             | A6                        | DeepSeaExpansion-1.12.2-Preview-A6.jar         | None                                     |
	| LCHIJA | jaff            | 1.7_for_1.12              | JustAFewFish-1.7_for_1.12.jar                  | None                                     |
	| LCHIJA | malisiscore     | 1.12.2-6.4.1-SNAPSHOT     | malisiscore-1.12.2-6.4.1-SNAPSHOT.jar          | None                                     |
	| UD     | cubicchunkscore | @@VERSION@@               | minecraft.jar                                  | None                                     |

	Loaded coremods (and transformers): 
CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.39.1-SNAPSHOT-all.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.4.1-SNAPSHOT.jar)
  
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.970.0-SNAPSHOT-all.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 419.67' Renderer: 'GeForce GTX 1660/PCIe/SSE2'
	Launched Version: forge-14.23.5.2838
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1660/PCIe/SSE2 GL version 4.6.0 NVIDIA 419.67, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 419.67
	OpenGlRenderer: GeForce GTX 1660/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by ghost** [comment]
It works now, I didn't realize I could change the version on the forge website. I grabbed the wrong one

**Comment by Niko-sk2x** [comment]
The only way I can imagine you could get the above log is by renaming the 6.5.x to 6.4.1 version.

**Comment by ghost** [comment]
I used the wrong website to get the Malisis Core. The first one I grabbed had a warning on it. I then realized I could change the version of the file I wanted on the curse forge website.

**Comment by Niko-sk2x** [comment]
Any website other than the mod author's website, curseforge minecraftforum or planetminecraft is very likely to be some sort of mod repost website, see https://stopmodreposts.org/index.html

**Comment by ghost** [comment]
https://ore.spongepowered.org/Dockter/MalisisCore/versions/1.12.2-6.4.1-SNAPSHOT/confirm?downloadType=0&api=false&dummy=dummy Could this be an unlisted website?

**Comment by Niko-sk2x** [comment]
I honestly didn't know they even had any forge mods there. This website is ok, but it mostly has sponge plugins. This is a snapshot version used internally probably by Almura, and it's not 100% equal to the CurseForge 6.4.0. It's probably 6.4.0 with the modifications from 6.5.x, just without the version number being changed.

**Comment by CRricker** [comment]
Got it. I understand this is not the place and that you’re most likely a busy person, but do you have any suggestions for terrain manipulation? I made a suggestion in the ideas and suggestions channel on the CC discord, and was wondering if there was already a way to do this or, if there wasn’t, if it was taken into consideration. One of the mod creators sort of acknowledged by reacting to it, so I don’t know if that means they might try it or something. If this isn’t the right place to ask, I’ll remove this comment.

**Comment by ghost** [comment]
Thank you for helping me
