### ISSUE TITLE
Kilometer+ tall oil spout with Buildcraft 7.99.14 and Cubic Chunks 821

### ISSUE THREAD

**Issue by AlexGreason** [Barteks2x/CubicChunks#342]
This occurs in the Custom Cubic overworld. The spout has a bottom (it terminates at that island), but does not have any top that I can find (hence the "+" in "kilometer+") It does not appear to be infinite, because when I teleported 10k blocks up it was not present, but because it takes several minutes for blocks to start loading after a teleport I have been unable to find the exact top.
Screenshot:
![2018-01-26_21 07 08](https://user-images.githubusercontent.com/5667993/35472913-69576190-033d-11e8-9fc8-1553f7b94eb6.png)
preset: 
[Exa-Islands-821-no_ores.txt](https://github.com/OpenCubicChunks/CubicChunks/files/1670140/Exa-Islands-821-no_ores.txt)
seed: 7171866076957742794
coordinates in screenshot
Fml-client-latest log:
[fml-client-latest.txt](https://github.com/OpenCubicChunks/CubicChunks/files/1670142/fml-client-latest.txt)

Note: The spout is weird and lumpy because it has not finished flowing yet. As I move further up, it updates the spout and it starts spreading out, I believe that if it was allowed to finish flowing it would be uniformly as thick as it is at its thickest point in that picture

**Comment by Niko-sk2x** [comment]
You enabled generating modded stuff in cubic chunks world. You do it at your own risk. There is a reason it's not enabled by default. Mods are free do do any stuff they want here. That includes generating HUGE stuff.

**Comment by Foghrye4** [comment]
@AlexGreason try to create issue in BuildCraft issue tracker. They could fix that.

**Comment by Niko-sk2x** [comment]
No they couldn't. This generator is not inteneded to be compatible. It's not supp;osed to be used they way cubic chunks uses it. What cubic chunks does here is a massive hack used in hope some stuff will work out just fine.
