### ISSUE TITLE
loadup crash.

### ISSUE THREAD

**Issue by border999** [Barteks2x/CubicChunks#343]
https://pastebin.com/uZYmRxb7
If you have questions, ask and I'll answer to the best of my ability.

**Comment by BaccarWozat** [comment]
1) Try with CubicChunks-1.12.2-0.0.821.0-SNAPSHOT-all.jar. The "all" gives the whole thing.
2) Also try with malisiscore-1.12.2-6.3.2.jar.
3) Not all the mods you are trying to play CC with have been tested and shown to work with it. It is better to start with a CC-only pack and add the mods one at a time unless you are sure they work (Chisel, etc.).

**Comment by border999** [comment]
Trying now, but I would like to have it on record that none of these mods seem to immediately stop working when Cubic Chunks is present. World gen on the other hand is &”&”$$@ impossible with how long it’s taking. Gave up after an hour and it not even leaving 0%.

**Comment by border999** [comment]
I will also heavily suggest compatibility testing with forestry. Because world generation always locks up or stalls when it gets to forestry.
Oh, since I'm running such a large modpack, you'll probably be hearing a lot from me until I able to generate a cubic chunk based world.
One more question. How many different options are there in the generation list will result in a cubic chunk based world when the mod is in?

**Comment by border999** [comment]
Correction, Forestry seems to stall on custom, not normal generation. This note was taken with only forestry, malisiscore, and cubic chunks installed.

**Comment by Niko-sk2x** [comment]
With CustomCubic, you are not supposed to enable modded generation. It's never going to work correctly.

With Default+CubicChunks/VanillCubic, some mods are still going to crash. I know why and it is fixable.

As for slow generation - it's also a known issue, a combination of generating more stuff, slower generation and slower lighting.

**Comment by border999** [comment]
Minecraft ran out of memory while it was generating the world. I had 6Gb dedicated to Minecraft.

**Comment by border999** [comment]
Possible memory leak during world generation?

**Comment by border999** [comment]
correction again. 5Gb, setting to 7 and trying again.

**Comment by Niko-sk2x** [comment]
Can you show the log? `fml-client-latest.log` and `latest.log` and if possible, launcher console output with logging level `DEBUG`

**Comment by border999** [comment]
Another correction, greenhouse module of Forestry still catching on something with the large mod pack and the normal cubic generation.

**Comment by border999** [comment]
https://gist.github.com/border999/0a37371643c82b9da7113e5e077a1ca6

**Comment by border999** [comment]
will bring up debug and other info as soon as possible.

**Comment by border999** [comment]
Quick question that may speed that up. Where would that info be logged, after another instance of Minecraft is launched after it.

**Comment by Velken** [comment]
Side note: your java 8 is really outdated.
You version: 1.8.0_25
Latest Java 8 Version: 1.8.0_162

**Comment by border999** [comment]
Just using the version of java that comes with minecraft now, but I'll upgrade now.

**Comment by Niko-sk2x** [comment]
I looked at the crash log again, this looks like you are trying to use the jar without `-all`, which doesn't contain the required libraries.
