### ISSUE TITLE
Suggestion: issue thread for all mods known to hinder world generation when with cubic chunks.

### ISSUE THREAD

**Issue by border999** [Barteks2x/CubicChunks#345]
First known issue mod. Forestry, something in the greenhouse module fails to load when creating the world takes too long.

**Comment by border999** [comment]
First known issue mod. Forestry, something in the greenhouse module.

**Comment by NoahJelen** [comment]
Galacticraft does not hinder CC generation, but it does cause extremely annoying rendering glitches above y=256. Here is some proof:
![2018-01-27_23 08 12](https://user-images.githubusercontent.com/29718341/35488454-9478fbae-0446-11e8-85e6-eb42ce9bf245.png)
![2018-01-27_23 08 28](https://user-images.githubusercontent.com/29718341/35488455-949968c6-0446-11e8-838f-02ec32559048.png)

I hope I'm posting this in the right place.

**Comment by border999** [comment]
Hopefully this will be. I'd also recommend you use the new update over on jenkins.
http://jenkins.daporkchop.net/job/CubicChunks/

**Comment by sirati97** [comment]
Seems to me as if Twilight Forest and Dim door make world generation take forever

**Comment by Niko-sk2x** [comment]
Wiki pages are the right place for this, not github issues. And for reporting issues, one compatibility issue with one mod per github issue.
