### ISSUE TITLE
Place to put compatibility test recommendations.

### ISSUE THREAD

**Issue by border999** [Barteks2x/CubicChunks#347]
Buildcraft
Natura
Ore shrubs

**Comment by Velken** [comment]
https://github.com/OpenCubicChunks/CubicChunks/wiki/Compatibility-for-mc-1.12.2
At the bottom there is already a area for mods not yet tested or that require more testing

**Comment by border999** [comment]
Again, this is a place to put recommendations for mods to  test. Because, unless the people that work on this github are gods, they aren't capable of looking at every single mod that comes out. This is to help focus them on the mods that are believed to be having issues with Cubic Chunks, allowing them to look into the issue more effectively and improve their mod.

**Comment by Velken** [comment]
The second table on the compatibility page also does that

**Comment by border999** [comment]
then make this the list you draw from.

**Comment by border999** [comment]
to put things on that list.

**Comment by border999** [comment]
totemic and binnie's mods (Forestry addon)

**Comment by border999** [comment]
IndustrialWires-1.6-24
immersivepetroleum-1.12.2-1.1.7
ImmersiveCables-1.12.2-1.2.0.1
Twilight forest
Compact Machines

**Comment by Velken** [comment]
You do know you can just go on the wiki and add them to the list right away, right? Like everyone else has been doing.

**Comment by border999** [comment]
Wasn't aware that was possible.

**Comment by HazyBlack** [comment]
@Velken @border999 

Do any of you know how do I make Custom Cubic as a world-gen in my server.properties?
I mean, what's its name? (For ex, know how in order to generate Biomes O' Plenty world gen you have to write BIOMESOP in the server)

**Comment by Dushess** [comment]
world type CustomCubic instead Default in server config.

**Comment by muzikbike** [comment]
Why is this still open if marked invalid?

**Comment by border999** [comment]
no clue
