### ISSUE TITLE
Suggestion: Config option to display what mod is currently being worked on when initial world generation is happening.

### ISSUE THREAD

**Issue by border999** [Barteks2x/CubicChunks#349]
This option would make it significantly easier to find which mods are throwing a wrench into a world's generation.

**Comment by border999** [comment]
Any mods seeing this?

**Comment by AlexGreason** [comment]
The developer's currently off somewhere, and has been since a few days before you posted this issue.
So, they'll probably see it when they get back. I don't know precisely when that'll be, it should be fairly soon.

**Comment by border999** [comment]
good to know

**Comment by Niko-sk2x** [comment]
If at all a good place for this would be forge, not cubic chunks.

**Comment by border999** [comment]
I've presented this to them as well, they stated that they would not. that you would have to be the one to do so because the reasons for needing such an option don't show up in any other mods really.

**Comment by border999** [comment]
If you are really unwilling to make this a config option on your end. I would suggest you take this up as an issue with the forge crew. And I will state for the record I tried already. See https://github.com/MinecraftForge/MinecraftForge/issues/4757#event-1479916752 for the evidence and discussion.

**Comment by Setadokalo** [comment]
To me, it doesn't seem at all like a cubic chunks problem - So if forge won't work on it, then it should most likely be an independent core mod.

**Comment by border999** [comment]
Then I would suggest anyone that can contact a modder that can do create such a mod does so and asks about making it..
