### ISSUE TITLE
GeneratorPipeline and PlayerCubeMap cleanup

### ISSUE THREAD

**Issue by Barteks2x** [Barteks2x/CubicChunks#35]
PlayerChunkMap is basically the vanilla equivalent of GeneratorPipeline, that also manages cubes for players. Information about which players load which cubes would be useful also for GeneratorPipeline. Currently they are separated, which causes some issues (like generating cubes in incorrect order).

What would make most sense is probably refactoring them into 2 different classes, one of them would deal with loading and generating chunks, the other with sending updates to client and keeping track of which chunks are loaded by which player as players move.

Doin gthat should also remove some duplicate work being done, which should improve performance.

**Comment by Barteks2x** [comment]
This should also fix #27

**Comment by Cyclonit** [comment]
I think the CubeManager should expose an interface for the WorldGenerator for prioritizing the generator queues. I have a working (using CustomCubic) multi-threaded GeneratorPipeline using one thread per GeneratorStage. These could invoke the CubeManager's prioritization interface at the same time, meaning that all stages would end up operating in the proper order. Merging all queues into one as proposed by #27 is not necessary.

**Comment by Barteks2x** [comment]
I already almost finished merging all queues into one. Multithreaded generation may not be a good idea, does population work with it? I explained the problems with in before. But if you really want to know if it's possible: yes, it is possible, people have done that. But this is way outside the scope of this project. I would see far greater benefits of using 32x32x32 cubes (which is actually reasonably easy to implement in bug-free way) than by implementing multithreading, which would likely result in many bugs.

I'm not sure how you could make the prioritization interface. The problem with current approach is that it wouldn't be easy to make the prioritization worm across different stages. For example, cube close to player should be processed earlier than cube far from player even if the cube close to player is 1000th in the queue in it's stage, and the one far from player is the first in it's own stage queue.

And even if you made the prioritization interface, what it would look like? I just can't imagine it. Prioritization is really just sorting. It needs to change dynamically as players move around the world.

I would also like to move away from the QueueProcessor thing, which initially only supported addresses and allowed duplicates, then I [patched together support for generic types](https://github.com/Barteks2x/CubicChunks/commit/952df3948dfb80d5c9080efe72a2c48420f4543f#diff-8b15a28b97eca1a6c2dbf74427a92e07R34) and [made it automatically discard duplicates](https://github.com/Barteks2x/CubicChunks/commit/952df3948dfb80d5c9080efe72a2c48420f4543f#diff-9091c19785d44e2989213184f1821eb0R28). I found it not flexible enough to do more than what it does now. Sorting it would be nearly impossible.

**Comment by Cyclonit** [comment]
I would add a method GeneratorPipeline.prioritize(Comparator comp). All this method needs to do is to sort the generator queues using this Comparator (regardless of how many there are). Using a single-thread system, having a single queue is a reasonable choice, as otherwise cubes in later stages that are farther away, might block cubes in earlier stages that are closer to the player. In my current multi-threaded system, this does not happen, because all stages can process cubes at the same time.

The 32³ change is appealing regardless.

I'll submit the PR in a moment (not merge ready) for you to have a look at and explain some choices I made there.
