### ISSUE TITLE
IC2 Rubber Trees generation does not determine

### ISSUE THREAD

**Issue by sirati** [Barteks2x/CubicChunks#354]
Profiling data: 
[IC2 Rubber Tree Endless Loop.zip](https://github.com/OpenCubicChunks/CubicChunks/files/1734915/IC2.Rubber.Tree.Endless.Loop.zip)

**Comment by Foghrye4** [comment]
IC2 Rubber Trees generation stuck in endless loop and halt a client?

**Comment by sirati** [comment]
From what I saw in the profiling data I cannot determine if we have a loop or just recursive method calls. But yes it is stuck while generating rubber trees resulting in no chunks being generated to a stage at which they are saved

**Comment by Rongmario** [comment]
IC2's worldgen was coded to be suitable with other height extension mods hence this happens. Source: Barteks

**Comment by Niko-sk2x** [comment]
Fixed in https://github.com/OpenCubicChunks/CubicChunks/commit/30fc76e6331b6997411493095cef7e7fccae5557
