### ISSUE TITLE
Transfering to Twillight Forest takes forever

### ISSUE THREAD

**Issue by sirati** [Barteks2x/CubicChunks#355]
This is due to CubeWatcher.removePlayer() taking far longer as expected
![image](https://user-images.githubusercontent.com/14129557/36355119-47e5f350-14d6-11e8-9ef8-b632530a190d.png)

Full profiling data:
[CubeWatcher.removePlayer.zip](https://github.com/OpenCubicChunks/CubicChunks/files/1734953/CubeWatcher.removePlayer.zip)

**Comment by sirati** [comment]
This method generally seems to be a major cause of lag:
![image](https://user-images.githubusercontent.com/14129557/36355160-5e81cc3c-14d7-11e8-9b03-fdc6c165dbfb.png)

**Comment by Niko-sk2x** [comment]
Is this still an issue?

**Comment by Niko-sk2x** [comment]
This shouldn't be an issue anymore. If this is still an issue, leave a comment here or create new issue.
