### ISSUE TITLE
Error while creating a custom cubic world

### ISSUE THREAD

**Issue by Dovencio** [Barteks2x/CubicChunks#363]
While I was creating a Custom Cubic world so I could have generation below level 0 I found an annoying bug while scrolling down the add ore GUI. If I scrolled down far enough Minecraft would just freeze up and crash issuing [this crash report](https://paste.ee/p/k8eXu).This would have not been a big problem if the preset button would just reject any block I manually type in. 

Plain links:
[https://paste.ee/p/k8eXu](https://paste.ee/p/k8eXu)

**Comment by Niko-sk2x** [comment]
Use newer version of cubic chunks. It's already fixed.
