### ISSUE TITLE
Dimensional Doors worldgen wont generate in customcubic worlds

### ISSUE THREAD

**Issue by theishiopian** [Barteks2x/CubicChunks#364]
Set the gen chance very high, still didnt work. Could be a symptom of an underlying worldgen problem, as apparently dd worldgen is supposed to be worldtype agnostic.

**Comment by Niko-sk2x** [comment]
It doesn't work in custom cubic by design. It's impossible to make it work reliably so CC doesn't fire any of the relevant events. If you want modded generation in cubic chunks - don't use custom cubic.

**Comment by theishiopian** [comment]
Ah, good to know. I was unaware, sorry about that.
