### ISSUE TITLE
ComputerCraft Turtles

### ISSUE THREAD

**Issue by ChickenManJordi** [Barteks2x/CubicChunks#366]
Found an issue where computer craft turtles do not work on a CC world. If you do tunnel 10 for example, they dont do anything. If i load up another world that isnt CC, they work just fine, Not sure if this is something you can fix but if it is thatd be great!

**Comment by ChickenManJordi** [comment]
Turns out its something with my server because it works in single player

**Comment by Niko-sk2x** [comment]
Doesn't mean that there is no issue. Just that it's not on singleplayer.
