### ISSUE TITLE
'Just a Few Fish' mod locks up Minecraft and lags computer

### ISSUE THREAD

**Issue by jgrimes900** [Barteks2x/CubicChunks#369]
Upon loading a world the game freezes and have to close Minecraft with the task manager. After doing so my entire computer goes laggy, Minecraft launcher won't launch Minecraft and have to restart my computer to fix everything.

I have only tested this on cubic flat generator.

OS : Windows 10
MC Version : 1.12.2

**Comment by DBotThePony** [comment]
please attach visualvm *.nps report (or use ![sampler](http://files.player.to/sampler-1.73.jar), do /sampler start, then /sampler stop and then /sampler export mylags)

**Comment by Niko-sk2x** [comment]
This mod very likely does custom mob spawning and will never work without changes to that mod.. I remember seeing issues with this mod before.
