### ISSUE TITLE
Freeze after World Generation is Finished

### ISSUE THREAD

**Issue by Rongmario** [Barteks2x/CubicChunks#373]
debug.log : https://gist.githubusercontent.com/Rongmario/3d499033c70762c5f53ba57ba95cef9c/raw/a8ab1463bccae9539cad38a63aac2f1bb40b5813/gistfile1.txt

latest.log:
https://gist.githubusercontent.com/Rongmario/fe1d9ff586e0d7af8b555e6b29943310/raw/21840a429c1b1679f4896b8f9582c3d8ef68fc4c/gistfile1.txt

**Comment by Niko-sk2x** [comment]
Mixin didn't load, probably didn't include something needed for it in compilation.
