### ISSUE TITLE
Crash with Dynamic Surroundings

### ISSUE THREAD

**Issue by Rongmario** [Barteks2x/CubicChunks#375]
https://gist.githubusercontent.com/Rongmario/da6107df6a68323ac319bb618b7244dc/raw/15ad5a794b0b48721e1d81c12c856f36c5ba3833/gistfile1.txt

Happened when I was walking exploring new chunks.

**Comment by BaccarWozat** [comment]
This has also happened to a member on my server. (DS is not in my modpack though.)
https://cdn.discordapp.com/attachments/388706158954938369/440872189022175244/crash-2018-05-01_06.47.39-client.txt

**Comment by Rongmario** [comment]
@BaccarWozat leave it here too: https://github.com/OreCruncher/DynamicSurroundings/issues/330

**Comment by 0xlsca** [comment]
https://pastebin.com/7R15i1JL

Crashes when loading a CC world.
I got CWG added in but that shouldn't meddle with anything in that regard. 
Startup is unaffected, which makes sense because the mod is targeting game-runtime.
