### ISSUE TITLE
Crash on World Load with Natura

### ISSUE THREAD

**Issue by oliverrook** [Barteks2x/CubicChunks#376]
I can confirm that Natura is not compatible with version 385. When loading a cubic chunks world, it gets as far as "Preparing Spawn Area 0%" and then no longer progresses, though it does continue to eat up more and more memory, so it causes a leak problem as well.

**Comment by Niko-sk2x** [comment]
Why did you close the issue?

**Comment by border999** [comment]
I agree, This is an issue that should be addressed
