### ISSUE TITLE
Crash with journeymap

### ISSUE THREAD

**Issue by Kabaril** [Barteks2x/CubicChunks#377]
This probably happens with every Minimap, happens when walking around.

The crashlog:
https://gist.githubusercontent.com/Kabaril/da13b1ee277e0e98ae9b18572f25a753/raw/f13747b0fecae1e8b10d872e48c63065323ce600/crash-2018-05-22_02.33.53-server.txt

**Comment by Rongmario** [comment]
Happens only with JourneyMap, Haven't occured on Antique Atlas for me.

**Comment by Kabaril** [comment]
Interesting, i didnt think that it would work at all. 
The problem is *i think* caused by loading the chunk your in, but when it loads a chunk above the light changes and it cant process it.

**Comment by Niko-sk2x** [comment]
The problem is really caused by JM being multithreaded and assuming that blocks directly from Chunk can be safely accessed from other threads. This is not true in cubic chunks.

**Comment by Niko-sk2x** [comment]
Fixed by JourneyMap in version 5.5.4
