### ISSUE TITLE
Thaumcraft Vis

### ISSUE THREAD

**Issue by Velken** [Barteks2x/CubicChunks#378]
Thaumcraft is not saving Vis data with cubic chunks. (All chunks have 0 vis). #

**Comment by Velken** [comment]
Recommended balance: Vis stored in each 16x16x16 chunk and make each chunk 1.5x less vis than normal chunks and make the recipe for the upgrade (which allows to get vis from adjacent chunks) harder to craft (since it goes from 8 neighbor chunks to 26).

**Comment by Niko-sk2x** [comment]
This issue has already been fixed by saving chunk capabilities.
