### ISSUE TITLE
Server worldgen broken in build 853

### ISSUE THREAD

**Issue by Aang23** [Barteks2x/CubicChunks#379]
Even if the world type is set to CustomCubic, it is the Vanilla generator / world type that is used. This also break on client sometimes.

**Comment by Niko-sk2x** [comment]
Becuase that version no longer contains CustomCubic. And you aren't supposed to use that version yet.

If you lost a world because of that, blame forge for not giving you a sensible warning. Or if it did, yourself for ignoring it.

**Comment by Aang23** [comment]
I was using it for testing purposes... I did not lose anything. So, how can I generate a Cubic world on the server ?

**Comment by Niko-sk2x** [comment]
You wait until the custom generator as separate mod is done and ready to use.
