### ISSUE TITLE
Crash when clicking "Customize" on Custom Cubic world setting

### ISSUE THREAD

**Issue by ProxyPlayerHD** [Barteks2x/CubicChunks#380]
[LOG](https://pastebin.com/rHfsn2b6) (should include all versions for Forge, the mod, malisisCore, etc)

there is nothing much to say, i just clicked it and it crashed

**Comment by Kabaril** [comment]
Using Forge 2705 works for me

**Comment by Niko-sk2x** [comment]
Already fixed. Duplicate of #341.
