### ISSUE TITLE
Qwestion

### ISSUE THREAD

**Issue by mcDandy** [Barteks2x/CubicChunks#388]
How are ores generated below Y=0?

**Comment by BaccarWozat** [comment]
Very carefully.

Serious answer: In CustomCubic worlds they generate based on where you put the sliders, but in other world types with CC checked, they aren't, it's just stone (or netherrack, etc.)

**Comment by mcDandy** [comment]
Thank you.

**Comment by mcDandy** [comment]
Thank you.
