### ISSUE TITLE
Galacticraft rockets crash when going above vanilla block limit

### ISSUE THREAD

**Issue by seancrain** [Barteks2x/CubicChunks#394]
As I expected, attempting to go above the standard block limit when attempting to travel between planets crashes the client.

Crash Report: [https://www.nosiphus.com/minecraft/crash-reports/crash-2018-09-20_21.25.59-client.txt](https://www.nosiphus.com/minecraft/crash-reports/crash-2018-09-20_21.25.59-client.txt)

Normally, the rocket exits at the atmosphere at around y=1200, but because the entity crashes before that, I cannot test to see if I can leave the atmosphere at the correct location.

@micdoodle8 @radfast I have no idea if you guys have any plans to support Cubic Chunks, but I thought I'd notify you about this just in case you want to support it.

**Comment by Niko-sk2x** [comment]
This is not really fixable on my end and galacticraft has multiple other issues with cubic chunks.
