### ISSUE TITLE
cannot compile mod

### ISSUE THREAD

**Issue by ProxyPlayerHD** [Barteks2x/CubicChunks#402]
why do we even have to compile it ourself, is there no normal download?

first i tired to run "gradlew setupCIWorkspace" which worked and was done after 20 sec. then i ran "gradlew build" which almost instantly failed. https://pastebin.com/ZqhLPAH1

**Comment by Foghrye4** [comment]
Try to clone project via Git instead of downloading a .zip or init Git in a directory.

**Comment by Foghrye4** [comment]
Normal downloads located here: https://discord.gg/gBUm6Z

**Comment by ProxyPlayerHD** [comment]
and that with git means what?

**Comment by Foghrye4** [comment]
It means run command ```git -clone https://github.com/OpenCubicChunks/CubicChunks.git```

**Comment by ProxyPlayerHD** [comment]
run it where? CMD?

i have never used any of these features. so don't exptect me to know how it works.

**Comment by Foghrye4** [comment]
You need to install Git first. And probably yes, in CMD. I'm using Ubuntu so I'm not sure.

**Comment by ProxyPlayerHD** [comment]
ok i'm still missing something, it doesn't recognize the "-clone" option

E:\Git>git -clone https://github.com/OpenCubicChunks/CubicChunks.git
unknown option: -clone
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

E:\Git>

**Comment by Foghrye4** [comment]
Try `--clone`

**Comment by ProxyPlayerHD** [comment]
same error.

is there some one time thing i have to run before i can do this?

**Comment by Foghrye4** [comment]
@ProxyPlayerHD here: http://www.mediafire.com/file/i7mg0kzjyf6q29m/CubicChunks-1.12.2-0.0.881.0-SNAPSHOT-all.jar

**Comment by Niko-sk2x** [comment]
`git clone https://github.com/OpenCubicChunks/CubicChunks.git`. Or just join our discord for all the download links you may ever want.

**Comment by Foghrye4** [comment]
Apparently Windows version of git uses another set of command. I can't help you.

**Comment by ProxyPlayerHD** [comment]
alright thanks

i never used discord so i tried this way

**Comment by Niko-sk2x** [comment]
And the real reason it failed is that you don't have JDK installed, only JRE. If you had JDK installed, it would compile successfully, and put some dummy version numbers because it couldn't determine the version without git repository.

**Comment by ProxyPlayerHD** [comment]
dammit, such a simple mistake
