### ISSUE TITLE
Optimized path navigator may cause server freeze when pushing entities through nether portal

### ISSUE THREAD

**Issue by Niko-sk2x** [Barteks2x/CubicChunks#403]
Most likely caused by trying to construct ChunkCache with very big coordinate range.

**Comment by Foghrye4** [comment]
Only hostile entities in survival mode?

**Comment by Niko-sk2x** [comment]
So far only happened when going through the portal on a horse, or when someone pushed d a horse through, and even that not every time.

**Comment by Foghrye4** [comment]
I suppose that with `"optimize_path_navigator":false` option everything is fine?

**Comment by Niko-sk2x** [comment]
Yes, it seems to work fine with that option set to false.

**Comment by Niko-sk2x** [comment]
Fixed by https://github.com/OpenCubicChunks/CubicChunks/pull/405
