### ISSUE TITLE
Crash with primitive mobs

### ISSUE THREAD

**Issue by Yoosk** [Barteks2x/CubicChunks#407]
Crashed while exploring world at y -350

https://gist.github.com/4c39fbd47137f5c6758a064917e31557

Modpack: All The Mods 3 - Remix 0.1.2*

**Comment by Niko-sk2x** [comment]
This mod creates a custom mob spawning algorithm, by copypasting and modifying vanilla one, properly fixing it needs new API in forge and changing such mods to use the API. 

CubicChunks also modifies that algorithm, and cubic chunks modifications aren't there in mod code. 

I've seen many mods do that, and even just for performance, this should be done by providing APIs mods need on forge side. Many implementations of this definitely don't help with performance.
