### ISSUE TITLE
Known compatibility with out-of-engine voxel render engines (e.g. chunkyrenderer)

### ISSUE THREAD

**Issue by diclophis** [Barteks2x/CubicChunks#410]
Is this mod, and the save games it produces compatible with any 3rd party voxel renderer suite?

**Comment by Niko-sk2x** [comment]
No. Most of them will probably see empty world. CubicChunks regions are in a different directory and in a different format (based on the same idea but different enough that even NBTExplorer is unable to read it).

**Comment by diclophis** [comment]
ok cool, thanks for the quick reply
