### ISSUE TITLE
forestry_1.12.2-5.8.2.362 locks up world gen CubicChunks-1.12.2-0.0.902.0-SNAPSHOT-all

### ISSUE THREAD

**Issue by border999** [Barteks2x/CubicChunks#412]
How to replicate. load both forestry and cubic chunks. try to create a world.

**Comment by Niko-sk2x** [comment]
Upload log file (debug.log).

**Comment by border999** [comment]
taking this elsewhere, only occurs with a combination of mods.

**Comment by Niko-sk2x** [comment]
If it doesn't occur without cubic chunks, it's still an issue that should be here.
