### ISSUE TITLE
Lockup report

### ISSUE THREAD

**Issue by border999** [Barteks2x/CubicChunks#413]
![screenshot 83](https://user-images.githubusercontent.com/11824584/48104566-18483f00-e202-11e8-81ff-862551d78660.png)
![screenshot 84](https://user-images.githubusercontent.com/11824584/48104567-18483f00-e202-11e8-9154-50cb140c7506.png)
![screenshot 85](https://user-images.githubusercontent.com/11824584/48104568-18e0d580-e202-11e8-85dc-89b6c4d98efa.png)
WIth the mods listed on the first two screenshots, world gen locks up at 15%.
When adding the three mods in the last screenshot, world gen locks up at 5%

**Comment by Niko-sk2x** [comment]
Can you upload debug.log file?

**Comment by border999** [comment]
so many problems, doesn't help that I keep putting all the mods back in and updating things. Here's a crash report for my latest attempt. This time it's immersive engineering. 
https://pastebin.com/yD6ALGrW

**Comment by Niko-sk2x** [comment]
Immersive engineering should work. Are you sure the same mods work fine without cubic chunks?

**Comment by Niko-sk2x** [comment]
The initial report was about worldgen locking up. What happened to that? Make sure what your issue is about before reporting it.

**Comment by border999** [comment]
[debug.log](https://github.com/OpenCubicChunks/CubicChunks/files/2564167/debug.log)

**Comment by Niko-sk2x** [comment]
Industrial craft world generation is incompatible because it's trying to generate it's ores in the whole height range of 1 billion blocks, all at once.

**Comment by border999** [comment]
would it be possible to turn off world gen for IC2?

**Comment by Niko-sk2x** [comment]
Look at IC2 config

**Comment by border999** [comment]
that works. Slowly readding mods. know if applied energestics works with cubic chunks?

**Comment by Niko-sk2x** [comment]
I didn't test it myself anytime recently but if it loads, the only thing known to not work is spatial storage.

**Comment by border999** [comment]
![screenshot 96](https://user-images.githubusercontent.com/11824584/48240666-a4449d00-e3a1-11e8-8680-a33a0a94da30.png)
![screenshot 90](https://user-images.githubusercontent.com/11824584/48240667-a4449d00-e3a1-11e8-92c7-60d814f2d221.png)
![screenshot 91](https://user-images.githubusercontent.com/11824584/48240668-a4449d00-e3a1-11e8-88de-868ec2962057.png)
![screenshot 92](https://user-images.githubusercontent.com/11824584/48240669-a4449d00-e3a1-11e8-9dfc-af8723935a32.png)
![screenshot 93](https://user-images.githubusercontent.com/11824584/48240670-a4449d00-e3a1-11e8-870a-24c3b4f1f96c.png)
![screenshot 94](https://user-images.githubusercontent.com/11824584/48240671-a4449d00-e3a1-11e8-9aa2-1e51e7ed4ab5.png)
![screenshot 95](https://user-images.githubusercontent.com/11824584/48240672-a4dd3380-e3a1-11e8-9b80-1f2ab933adc0.png)
![screenshot 97](https://user-images.githubusercontent.com/11824584/48240677-a9095100-e3a1-11e8-8e36-084db1f7202b.png)
![screenshot 98](https://user-images.githubusercontent.com/11824584/48240678-a9a1e780-e3a1-11e8-88ad-1829464b2d2f.png)
also, mind checking to see if anything sticks out as incompatible?

**Comment by Niko-sk2x** [comment]
Way too many mods. It's unlikely to even load. Look at the wiki for compatibility list. 

The first thing I found that is definitely not going to work is just enough IDs. It will appear to work but will corrupt your world.

**Comment by Redd56** [comment]
I know some forestry ardons dont work well with cc alongnwith ae2 meteor gen

**Comment by Redd56** [comment]
Thats your issue

**Comment by Niko-sk2x** [comment]
Then report them properly, with clear steps to reproduce the issue.

**Comment by Niko-sk2x** [comment]
Each mod as a separate issue.

**Comment by Redd56** [comment]
The ae2 meteor issue has been documented alot. And it may just be that some forestry addons together cause issues. Idk yet havent had any time to check

**Comment by Niko-sk2x** [comment]
It can only be considered cubic chunks issue if it doesn't happen without cubic chunks. I'm not sure what issues you are talking about. If they are compatibility issued with cubic chunks, make a separate issue with clear steps to reproduce the issue with minimal amount of mods. If it's a world generation issue that may hard to find also provide seed and location.

**Comment by Redd56** [comment]
For the ae2 meteor issue. It locks the second it gens a meteor. Someone said that it looked like there was meteors everywhere.... I think i know the issue tho. Ima make a thing for it
