### ISSUE TITLE
pistons dont work right period

### ISSUE THREAD

**Issue by Redd56** [Barteks2x/CubicChunks#426]
simply put pistons dont have the exact same mechanics as they do in the vanilla game. or without cc in general. for some reason some part of the code either messes with the update order of the pistons or something.. which makes lots of things broken

**Comment by Redd56** [comment]
plz fix before you anger the gods (aka the technical minecraft community that does complex redstone)

**Comment by Niko-sk2x** [comment]
Can you show example piston circuit that shows the problem?

**Comment by Redd56** [comment]
https://www.youtube.com/watch?v=yxqSK4j3WT8

**Comment by Redd56** [comment]
https://youtu.be/C45GYl_qGx8
just putting it here again

**Comment by Niko-sk2x** [comment]
Fixed
