### ISSUE TITLE
[need more information] Sometimes server sends columns/cubes in the wrong order, causing client chunk corruption

### ISSUE THREAD

**Issue by Niko-sk2x** [Barteks2x/CubicChunks#428]
Like this 
![bug_corrupt](https://user-images.githubusercontent.com/1349112/52294517-dd2ce780-2979-11e9-88d9-fce9da19e016.png)

If you are affectted by this bug the following information may be useful:
 * CubicChunks version
 * MinecraftForge version
 * Java version
 * Your hardware
 * Operating system
 * Your network comnection speed and reliability at the time it happened
 * **Other mods installed** both on the client and on the server
 * `debug.log` file (if you are using Twitch launcher, `latest.log`, and next time use Mojang's launcher or MultiMC)
 * The server you were on, or if you were on singleplayer
 * How many players were on the server, was the server lagging? If you know the information, was it TPS issue or network lag? Did you have FPS drops?
 * Screenshots, if you have any
 * Have you been generating new chunks? Loading existing chunks for the first time after an update? Loading chunks after a long time of server inactivity?
 * **Force a crash with F3+C and upload the crash report file**, this will already provide a lot of accurate information about your system. Doesn't need to be the same run of Minecraft that had the issue, just the same versions of the same mods.

If for any reason you don't want to share this detailed information, you can post only the information you want. Anything is still better than nothing.At minimum, post an information that you are affected by this issue. If it happens multiple times, either exit existing comment to include more information, or make new one.

I cannot reproduce this but but I've been getting a lot of reports of it for a long time, and it happened for me a few times, so I'm trying to find some common factors.

Don't spam this place with anything other than those details provided. This is purely a place for me to collect the data.

**Comment by Foghrye4** [comment]
As Da Dragon wrote:
You can break a block in glitchy cubes. Doing so will cause block to dissapear without trace. Which means: 1. Corruption is client-side only.
2. It is unrelated to render caches. Client XYZ map is affected.
Logging out and back fix corruption. Which means that corruption is either unrelated to server state, or purging player cube watchers map fix issue.
Current XYZ map implementation return only cubes with position  matching requested coordinates. Cube position is immutable. Since relogging fix issue that means that network handler assign incorrect coordinates to recieved cube data.

**Comment by Niko-sk2x** [comment]
This much I already know. The problem is what causes the issue to be possible in the first place. I also know that it's actually the server sending cubes/columns in the wrong order.

**Comment by Niko-sk2x** [comment]
Most likely fixed with https://github.com/OpenCubicChunks/CubicChunks/commit/166f77f3e822abda590ac5b85ee4796d0df6bb9c. Will be reopened if/when someone reports it again.

**Comment by Niko-sk2x** [comment]
Still an issue, now with steps to reproduce, provided by TCW server player:
 * create a local server with 2 players, one can be stationary
 * move around the stationary player generating new chunks

Usually, out of order cubes get sent to the moving player within seconds.
