### ISSUE TITLE
Crash Report - Cubic Chunks and Dynamic Stealth

### ISSUE THREAD

**Issue by Xorbah** [Barteks2x/CubicChunks#433]
Title. I know a lot of mods are rather incompatible with CC, but figured this was worth reporting. Here's the crash log.
[crash-2019-03-27_03.43.30-server.txt](https://github.com/OpenCubicChunks/CubicChunks/files/3012279/crash-2019-03-27_03.43.30-server.txt)

**Comment by Niko-sk2x** [comment]
And that's what happens when 2 mods try to avoid transforming the same class. 

This will be fixed.

**Comment by Xorbah** [comment]
Awesome! Much appreciated.

**Comment by Niko-sk2x** [comment]
This can only be fixed by the other mod. Leaving it open for now.
