### ISSUE TITLE
1.12.2 Crashes on Startup

### ISSUE THREAD

**Issue by 2tsuru** [Barteks2x/CubicChunks#434]
I'm on Windows 10, Java Edition. 
I don't really know what is causing this but no matter what it keeps crashing even before the Mojang symbol pops up.

https://pastebin.com/j8y0nYqT

I have attached a copy of the crash report. Please help

**Comment by Niko-sk2x** [comment]
Crash report isn't enough to say for sure what is wrong. `debug.log` file is needed for that.

The most likely case is that you have outdated forge and unsupported version of OptiFine installed together, so it crashes before forge can tell you that you need newer version of forge.

**Comment by 2tsuru** [comment]
Okay, where do I get the debug.log file from?

Also my forge version is 1.12.2 but I will reinstall anyways just to be safe.

**Comment by Niko-sk2x** [comment]
debug.log file should be in logs directory. If it's not there, then your forge version is so old it has that file under different name.

1.12.2 is Minecraft version. Forge has many different versions and keeps being updated. Your forge version is `14.23.3.2655`. Latest is `14.23.5.2823`, recommended is `14.23.5.2768`.Your version is from almost a year ago.

**Comment by 2tsuru** [comment]
Thank you, it's working now.
