### ISSUE TITLE
Kettle (Paper + Forge) compatibility

### ISSUE THREAD

**Issue by DarkoGNU** [Barteks2x/CubicChunks#439]
I have been warned that OpenCubicChunks is incompatible with Bukkit/Spigot, and Kettle ([link](https://github.com/KettleFoundation/Kettle)) is still "very raw". The server crashes at startup with OpenCubicChunks. It may have something to do with Sponge, as I see some "spongepowered" things in logs. Making Cubic Chunks compatible with Kettle is probably hard and not very important (I just wanted to run an experimental server with some plugins). I tested the mod with plain Forge server and it works fine.
Logs:
https://pastebin.com/XQ3WrzuE
https://pastebin.com/wwbZsLc3

**Comment by Niko-sk2x** [comment]
This is not going to work and I have no intention to ever support bukkit and it's derivatives.

Kettle patches are extremely aggressive, and generally done in a way that is going to cause a lot of issues. On top of that the bukkit patches modify a lot of the same code that cubic chunks needs to modify. A lot of the same issues as with sponge, except the bukkit API has never been designed with anything like cubic chunks in mind (sponge API actually has features for cubic chunks based implementation).

The reason it crashes is that Mixin detects that it can't apply some of the changes required by cubic chunks.

Some minimal bukkit support shouldn't take more than a few days of work, but as I said - this is not something I plan to support. It's also not going to work well without special support from plugins (it's likely to be even worse than forge mods).
