### ISSUE TITLE
Incompatibility with phosphor

### ISSUE THREAD

**Issue by border999** [Barteks2x/CubicChunks#444]
https://pastebin.com/xTu8dhRM

**Comment by Niko-sk2x** [comment]
Upload the whole log file (debug.log)

**Comment by Niko-sk2x** [comment]
This is also not an IC2 issue. IC2 just happens to be involved in loading the class. The real error has been caught and logged earlier (most likely by optifine). Your modpack is also way too big.

**Comment by border999** [comment]
alright attempting loadup again without optifine but with IC2 and cubic chunks

**Comment by border999** [comment]
[crash-2019-05-29_15.36.37-client.txt](https://github.com/OpenCubicChunks/CubicChunks/files/3235107/crash-2019-05-29_15.36.37-client.txt)

**Comment by border999** [comment]
[debug.log](https://github.com/OpenCubicChunks/CubicChunks/files/3235109/debug.log)

**Comment by border999** [comment]
still crashed

**Comment by YoYoK3nny** [comment]
@border999 
You're using a mod that is incompatible with CubicChunks.
Remove JustEnoughIDs (which is specifically listed as incompatible with CubicChunks on CurseForge) and it's integrations mod and the modpack **_might_** stop crashing.

Then again, there may be further crashes related to other mods that are incompatible with each other.

**Comment by Niko-sk2x** [comment]
phosphor is the incompatibility that actually causes the crash. And NEID and JEID aren't compatible with the version on curseforge. NEID will work with next version, JEID, maybe partially.
