### ISSUE TITLE
world gen lockup

### ISSUE THREAD

**Issue by SturdyFool10** [Barteks2x/CubicChunks#449]
I am currently having infinite load times with a modified direwolf20 modpack that I removed forestry and other dependents from

**Comment by SturdyFool10** [comment]
World gen to be more exact, sorry for not clarifying

**Comment by Niko-sk2x** [comment]
This is most likely Industrial Craft 2. The only fix for now is disabling IC2 worldgen. You will also find a few other incompatible mods, or only partially compatible mods.

**Comment by Niko-sk2x** [comment]
Fixed in https://github.com/OpenCubicChunks/CubicChunks/commit/30fc76e6331b6997411493095cef7e7fccae5557
