### ISSUE TITLE
Dynamic trees dont spawn when using Custom Cubic world generation setting

### ISSUE THREAD

**Issue by NikTink** [Barteks2x/CubicChunks#450]
Having dynamic trees installed with this mod and selecting the "custom cubic" world type prevents dynamic trees from spawning it's trees instead of the vanilla ones. Dynamic trees do spawn when using normal world generation. These can also be grown from acorns etc. Only world generation does not agree

**Comment by Niko-sk2x** [comment]
https://github.com/OpenCubicChunks/CubicDynamicTreesAddon is intended to solve it but it needs an update to be compatible with latest DT versions.

**Comment by Niko-sk2x** [comment]
Updated and available on curse now.
