### ISSUE TITLE
CubeWatchEvent not always fired

### ISSUE THREAD

**Issue by Johni0702** [Barteks2x/CubicChunks#451]
Looking at CubeWatcher internals, I came across these lines which appear to send the cube to the player while never firing the CubeWatchEvent (haven't actually tested it, just a suspicion):
https://github.com/OpenCubicChunks/CubicChunks/blob/5cef9e0256f914b527c0787dc3b060968686f6f8/src/main/java/io/github/opencubicchunks/cubicchunks/core/server/CubeWatcher.java#L120-L124
In contrast (when the cube is first loaded):
https://github.com/OpenCubicChunks/CubicChunks/blob/5cef9e0256f914b527c0787dc3b060968686f6f8/src/main/java/io/github/opencubicchunks/cubicchunks/core/server/CubeWatcher.java#L219-L222

**Comment by Niko-sk2x** [comment]
That should be easy to fix.
