### ISSUE TITLE
Configure world height in-game

### ISSUE THREAD

**Issue by muzikbike** [Barteks2x/CubicChunks#460]
It's possible to modify the height and depth limit of a world by modifying a file in the world. Since this is a per-world setting, could it be made customizable within the customisation screen (within supported limits)?

**Comment by muzikbike** [comment]
Is this fixed?

**Comment by Niko-sk2x** [comment]
Yes, fixed in https://github.com/OpenCubicChunks/CubicChunks/commit/aca66ff9721fa926e43246f54247b268d5e87f51
