### ISSUE TITLE
Stop game from crashing/kicking player when surpassing 30 million blocks

### ISSUE THREAD

**Issue by muzikbike** [Barteks2x/CubicChunks#461]
When Cubic Chunks is played with other mods active that move the world boundary out to farther than the vanilla limit of 30000000 (for example https://github.com/ThisTestUser/FarLandsMod), surpassing this number can cause the game to immediately freeze or kick the player for being in an illegal position.

While this can be mitigated by deleting the MixinNetHandlerPlayServer line from cubicchunks.mixins.fixes.json, I find this to be a rather hacky solution. I think it would be better as some sort of option in-game or in a config file, preferably with a reasonably large warning that surpassing this limit may cause major issues in multiplayer and is not supported.

**Comment by Niko-sk2x** [comment]
I'm still undecided between a strict "no" and "maybe. Considering the amount of time I'm going to spend saying "no", it's probably easier for me to just make it work.
