### ISSUE TITLE
"Failed loading NBT Data" or "The game crashed whilst exception ticking world Error: java.lang.IllegalArgumentException"

### ISSUE THREAD

**Issue by ghost** [Barteks2x/CubicChunks#463]
Hello.
I have a few Problems.
Since a few Days, my Game crashes, if I set my vertical Render Distance higher up than 3. That isn't that bad if I can still play. But since today, I tried to load my world, but I couldn't, because the Game instantly crashed. I tried pulling down both types of Render Distance to 2, but it would still crash. There were different Kinds of Error Messages: "Failed loading NBT Data" or "The game crashed whilst exception ticking world Error: java.lang.IllegalArgumentException".
The Crash report is in the File attached
[crash-2019-08-29_10.25.43-server.txt](https://github.com/OpenCubicChunks/CubicChunks/files/3554658/crash-2019-08-29_10.25.43-server.txt)

**Comment by Niko-sk2x** [comment]
This looks like your world save file is corrupted. Immediately make a backup. If you want help solving this, you can join the discord server (link in readme). Here is not the best place for it.
