### ISSUE TITLE
Crash with Better Portals

### ISSUE THREAD

**Issue by Hyxaru** [Barteks2x/CubicChunks#467]
Reference from:
https://github.com/Johni0702/BetterPortals/issues/363

**Comment by Niko-sk2x** [comment]
This is actually caused by CWG far plane view mod, go report it there. It's invoking vanilla generator on it's own threads which simply isn't going to work.

**Comment by Hyxaru** [comment]
Tried to create another portal again with BP and the world keeps crashing from now on. I temporarly removed far plane view. Is this crash of a different cause?
[crash-2019-09-23_17.41.47-server.txt](https://github.com/OpenCubicChunks/CubicChunks/files/3642949/crash-2019-09-23_17.41.47-server.txt)

**Comment by Niko-sk2x** [comment]
Yes. This is hybrid world breaking something.

**Comment by Hyxaru** [comment]
Seems to happen when I create a (Better Portals) twilight forest portal only.

**Comment by Niko-sk2x** [comment]
It's hybrid world issue. Not better portals.
