### ISSUE TITLE
Support for non-cubicchunks clients

### ISSUE THREAD

**Issue by logmms** [Barteks2x/CubicChunks#471]
Is it possible to run this mod on a forge server without the client having to have the mod installed? When I try this I get the error:

 Disconnecting Player: This server has mods that require FML/Forge to be installed on the client: [CubicChunks]

**Comment by BaccarWozat** [comment]
Not really.

**Comment by Niko-sk2x** [comment]
No, it's not possible (and probably won't be implemented, even if there are theoretical ways to do something like this)
