### ISSUE TITLE
Extreme lags (game hangs for 1-2 seconds every 5-6 seconds)

### ISSUE THREAD

**Issue by Leonetienne** [Barteks2x/CubicChunks#476]
no other mods besides forge installed,
no resource pack,
fresh map,
running on ryzen 1600x, 32gb ddr4 3200mz, rtx 2070 super

**Comment by Leonetienne** [comment]
Edit: Only occurs while walking around, eg constantly loading new chunks and unloading old ones

**Comment by DaMatrix** [comment]
Sounds like garbage collection to me, what are your JVM arguments?

**Comment by sa-shiro** [comment]
It would be helpful, if you provide:
* CPU (its definetly **not** ryzen 1600x)
* JVM arguments
* Crash log
* Debug log

Crash log located at: **minecraft\crash-reports**
Debug log located at: **minecraft\logs**

**Comment by Leonetienne** [comment]
> Sounds like garbage collection to me, what are your JVM arguments?

Standard minecraft launcher "play" button. Didn't change anything. -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M


> It would be helpful, if you provide:
> 
> * CPU (its definetly **not** ryzen 1600x)
> * JVM arguments
> * Crash log
> * Debug log
> 
> Crash log located at: **minecraft\crash-reports**
> Debug log located at: **minecraft\logs**

Why wouldn't it be a 1600x?

The crash logs folder has no recent entries, since the game is not crashing. Just lagging. The latest entry is from waay before installing cubic chunks.

I can't create a pastebin link for the debug log because it's just too big.
Here is a wetransfer link: https://wetransfer.com/downloads/ae530be5e033e34c8c3af6ca461a349220191226023603/6854c9998abf611ad3227b30c0d3d9f920191226023603/84ade3 (valid 7 days from posting)

**Comment by sa-shiro** [comment]
you can simply use github gists: https://gist.github.com/

~~you said the debug log is from before installing cc - was it lagging there?
please provie an up-to-date log~~ you mean your crash log or?

 minecraft@1.12.2,FML@8.0.99.99,forge@14.23.5.2847,cubicchunks@1.12.2-0.0.970.0-SNAPSHOT,worldedit@6.1.10-SNAPSHOT,mcp@9.42

* update your cubicchunks (join the discord and get the newest version)
* ~~where is your malisis core?~~ NVM it's needed for CWG not CC my bad
* worldedit doesnt work well with cc

Maybe try to increase RAM, it may be the issue: you shouldn't run modded Minecraft with standard Minecraft Xmx > increase it to 3-4GB or more

**Comment by Leonetienne** [comment]
I don't have a crash log because the game didn't crash.
The debug log I've sent is from just an hour ago, while i went exploring and having laggs. Less than when opening this issue but still every minute multiple seconds freezing.

Sure, why not. I will increase the ram tomorrow to something like 20gb just to be sure lol. But not today, it's 4am

**Comment by Leonetienne** [comment]
Yes, it appears to be the ram.
When i assigned it 20gb, it instantly jumped to 11gb usage and the hard lags were gone. Still stutters sometimes but maybe this is just the ryzen gen1 cpu

**Comment by sa-shiro** [comment]
That it raises up to 11GB RAM usage is incredible questionable with just 2 mods

I'm running 180 with shader on 5-10GB max usage xD

Maybe try to update your Java and change the default Java path in profile settings (use the 64bit offline Installer and maybe try to use OpenJDK instead of Java (<-- it doesn't matter if you install JRE or JDK you just need to point to: bin/javaw.exe (JRE isn't even present since Java 12+ tho))) ---> you need to use Java 8 tho, Forge 1.12 runs on Java8

It would be stage tho, if the CPU causes such a high RAM usage for Java xD

**Comment by Leonetienne** [comment]
> That it raises up to 11GB RAM usage is incredible questionable with just 2 mods
> 
> I'm running 180 with shader on 5-10GB max usage xD
> 
> Maybe try to update your Java and change the default Java path in profile settings (use the 64bit offline Installer and maybe try to use OpenJDK instead of Java (<-- it doesn't matter if you install JRE or JDK you just need to point to: bin/javaw.exe (JRE isn't even present since Java 12+ tho))) ---> you need to use Java 8 tho, Forge 1.12 runs on Java8
> 
> It would be stage tho, if the CPU causes such a high RAM usage for Java xD

After a bit of mining it went up to 12.5 lol

I thought the minor stutters could be caused by the relatively old cpu falling behind generating new chunks. Not the high ram usage.

I have technically two mods. Practically one. Forge and CubicChunks.
When i run feed the beast (200 mods) it only goes up to about 16gb lol.

Maybe because i have the XZ and Y render distance set to 16?

Side note:
Just imagine cubic chunks AND feed the beast. These two together would be **so** goddamn cool, but tbh i don't see all these mod devs adapting to CC except mojang somehow makes CC vanilla. Also i would not be sure if 32gb ram would be sufficient hehe

**Comment by sa-shiro** [comment]
Usually you shouldn't need more than 12GB on <200mods and even for 300 mods, 12-14GB should be fine even with 1024x HD texture pack and ultra shader 

It's Ryzen 5 1600x or? As I said there's no Ryzen 1600x tho 

I am on a ryzen 3 2200G and yours is way better and at least seems to perform way worse -> I don't think your issue is the CPU (If yours is the Ryzen 5 1600x 6 core 12 threads )

What you can try:
* Open Task manager
* Go to Performance > CPU
* Is "Virtualization" enabled?

If it's not, you should definetly activate it, cause it boosts your whole machine up and everything will be faster and better etc 
You can activate it in your UEFI / BIOS settings

**Comment by Leonetienne** [comment]
It is the Ryzen 5 1600x.
Virtualization is disabled. I thought it was one of these VM things

**Comment by sa-shiro** [comment]
It is used by VMs too, but not only: your whole PC profits from it
And Java runs in an VM so it proffits from virtualization :DD that why its called JVM arguments as example ^^

**Comment by Leonetienne** [comment]
Will check this definitely in the bios next time booting up.

**Comment by DaMatrix** [comment]
the JVM is not a virtual machine in that sense, virtualization is of no relevance here. i can almost guarantee that this is an issue with garbage collection somehow.

**Comment by sa-shiro** [comment]
It's not a real virtual machine like OpenBox etc, but it runs in a "virtual machine"
And CPU virtualization could be the issue
I had lots of people running on low performance, because virtualization was disabled. They were amazed after the performance increase by enabling it

Why should it be the garbage collection, if he runs only "Vanilla" args with only increased ram while having the newest forge / Java? It makes no sense tbh, then we all would have that issue

**Comment by Leonetienne** [comment]
Actually encountered a new issue. Maybe just a wrong config setting? Somehow there are just stones under 0. No caves, no dirt, no gravel, no stone variants and not even ores. Or is this by design?

**Comment by DaMatrix** [comment]
the JVM does not utilize virtualization, as virtualization is intended for allowing nested systems to be run without the need to emulate the processor in hardware, and therefore can only be when the code being virtualized is intended for the host CPU. java bytecode cannot be run on hardware directly (unless you're using one of those weird ARM chips with jazelle), and as such cannot benefit from virtualization. the JVM uses a JIT compiler to compile java bytecode to native code at runtime, but still does not require hardware virtualization at any point in the process.

**Comment by sa-shiro** [comment]
> Actually encountered a new issue. Maybe just a wrong config setting? Somehow there are just stones under 0. No caves, no dirt, no gravel, no stone variants and not even ores. Or is this by design?

That's by default.
To get ores and caves etc, you need to download Hybrid + CubicWorldGen mod too (and it needs malisis core, Hybrid needs flamelib )

Edit:
Hybrid = makes you able to use CWG presets with other generators like Standards BoP etc

CWG = customisable generation from -minY to +maxY

**Comment by Leonetienne** [comment]
Ok thanks, will definitely download cwg aswell

**Comment by Niko-sk2x** [comment]
As for the incredibly high memory usage - G1GC tends to do that. It will use a lot of heap if it can get closer to the specified gc pause time. If you don't like it using so much memory, give it 4GB.

Also the amount of memory used by CC depends on render distance, render distance around 20 may use more than 2GB of RAM.
