### ISSUE TITLE
End cities not generating 

### ISSUE THREAD

**Issue by Niko-sk2x** [Barteks2x/CubicChunks#484]
Report from discord: end cities don't generate even in vanilla worlds with CC installed. Seems to be caused by noncritical mixin config (!?).

**Comment by Niko-sk2x** [comment]
From discord 

> @Barteks2x when i removed "common.MixinChunkPrimerOptimization", it worked

**Comment by KaPoof** [comment]
Where do you go to remove this?

**Comment by Niko-sk2x** [comment]
This is in cubic chunks jar file, in noncritical mixin config json file. But you have to be careful about syntax.

While it is a workaround, it's not an easy one so this needs to be fixed.

**Comment by AsheX1** [comment]
mmmm i can say wen reading this and reseting the end more then once then removing that line fixed it

some more info on this what and how i was running the end world

1: end was blacklisted so no CubicChunks there
2: deleting end world folder and reseting NBT data for end world
the above steps are done 5 time's
result no end city's every time
then 1 last time repeat the steps above + removing the line common.MixinChunkPrimerOptimization
in CubicChunks jar from cubicchunks.mixins.noncritical.json fixed the it now end city's generate 

this was for a server using cc1055 build but also seems to work for single player

still have no idea what MixinChunkPrimerOptimization does but server is still running fine with 100+ mods now

**Comment by muzikbike** [comment]
wasnt there a recent patch to fix this?

**Comment by AsheX1** [comment]
> 
> 
> wasnt there a recent patch to fix this?

yes but its still the same 1055 version i think just that line get removed so noobs don't need to do it and mess up the syntax

**Comment by AsheX1** [comment]
they have done 2 things 1
CC1056: Made world height limits configurable.
CWG127: Generate bedrock at the bottom of the world
build 1056

and then they re-upload that version removing the mixin line so end city's generate again in normal worlds
