### ISSUE TITLE
Generate chunks from command line

### ISSUE THREAD

**Issue by TheGreatRambler** [Barteks2x/CubicChunks#487]
I have looked at [mcexplore](https://github.com/DMBuce/mcexplore/blob/master/mcexplore.1.txt) and [pymclevel](https://github.com/mcedit/pymclevel/blob/master/mclevel.py), and they both appear to only support vanilla maps, in addition to only supporting setting the location of the player rather than loading specific chunks. I am wondering if there is a concise way to do this from the command line that supports cubic chunks. If I have to make a mod, then let me know.

**Comment by Niko-sk2x** [comment]
Mcexplore should work. It won't allow specifying Y range but can be modified to do it. 

Aside of that CC config allows to specify generation range for spawn area. So it can generate more chunks at a time. 

Making gorge pregen command work is also planned.
