### ISSUE TITLE
Crash upon startup [1.12.2]

### ISSUE THREAD

**Issue by varappdev** [Barteks2x/CubicChunks#491]
I found an issue regarding dynamic surroundings and I did what it said there, but it still crashing. Can you please tell me the cause and/or fix this? 

Crash report generated by VanillaFix: https://paste.dimdev.org/itaxinikuy.mccrash
Latest debug log: [debug.log](https://github.com/OpenCubicChunks/CubicChunks/files/4408964/debug.log)
Latest.log: [latest.log](https://github.com/OpenCubicChunks/CubicChunks/files/4408970/latest.log)

**Comment by Niko-sk2x** [comment]
This is caused by outdated VanillaFix version.
