### ISSUE TITLE
The Mod does not appear in the search function of curse

### ISSUE THREAD

**Issue by maxZ-2020** [Barteks2x/CubicChunks#494]
It does not come up when I enter "cubic" "cubic chunks" "OpenCubicChunks"

You are missing out on a lot of "for free" attention.

I did not know, that this mod was revived until a couple of weeks ago. And only because I searched hard.

**Comment by SupremeMarshal** [comment]
When I search Cubic Chunk in google, it give me this link as the first link: https://www.curseforge.com/minecraft/mc-mods/opencubicchunks

**Comment by Niko-sk2x** [comment]
Not much I can do about it. CurseForge doesn't like alpha versions and does a very good job at hiding them.
