### ISSUE TITLE
Is there a pre-alpha 1.14.x version

### ISSUE THREAD

**Issue by Vricken** [Barteks2x/CubicChunks#500]
I am working on a project and i am currently stuck if there is no possible way of downoading the 1.14 ver of this mod.

**Comment by DaMatrix** [comment]
the 1.14 version isn't just unstable, it doesn't work at all. updating is going to require a significant rewrite of the mod, and will likely be far more difficult than previous minecraft versions were.

**Comment by Niko-sk2x** [comment]
Just to give you an idea of the current state of 1.14+:

The version on github just trivially changes the build limit, without making any other corresponding changes. So there is no vertical chunk loading,sections beyond vanilla range don't save, they don't render, and aren't sent to clients. It was basically just a small test to verify that the very basic development setup works.

The version I have on my system has some minimal work in progress chunk data packets and the very beginning of an attempt ad 3d chunk loading. And is nowhere near being able to compile it, let alone run.
