### ISSUE TITLE
[1.12.2] can't use world edit under y=0 (can use above y=256)

### ISSUE THREAD

**Issue by TensorialYew8** [Barteks2x/CubicChunks#501]
I am trying to use worldedit under y=0 and on worldedit page I asked 

realTensorialYew8  #1779
I see is your latest version WorldEdit 6.1.10 (For MC 1.12.2) you can build above 256.
I was wondering will you update world edit so it can work under y=0 (bedrock) (eg. CubicChunks)
Thank you

and got a response of 

me4502  #1784
In reply to realTensorialYew8:

 You already can, when CubicChunks is installed they set the minimum and maximum world size within worldedit, so if it’s not set they’re not setting it correctly

I looked around in the configs of both world edit and cubic chunks but could not change it myself

I was wondering if you can take a look into this matter 
Thank you

Example video: https://youtu.be/5NP0DNhVMno

![2020-05-10_19 33 10](https://user-images.githubusercontent.com/43445082/81519367-9cebb000-9306-11ea-9b3c-5ebea60024b6.png)

**Comment by Niko-sk2x** [comment]
A build of this https://github.com/EngineHub/WorldEdit/pull/511 is already floating around but not available from official sources. Closing as I can't fix it in CC.
