### ISSUE TITLE
Implement Heightmaps

### ISSUE THREAD

**Issue by NotStirred** [Barteks2x/CubicChunks#511]
Implement heightmaps, as it has been entirely ignored up until now.

**Comment by CorgiTaco** [comment]
Understand & reimplement the 1.12 heightmap implementation seems to be the best approach

**Comment by NotStirred** [comment]
The implementation has changed as discussed in discord [here](https://discord.com/channels/316679487955927050/317206370359443458/774082783106170941)

**Comment by NotStirred** [comment]
merged https://github.com/OpenCubicChunks/CubicChunks/pull/604
