### ISSUE TITLE
Add vertical view distance

### ISSUE THREAD

**Issue by NotStirred** [Barteks2x/CubicChunks#519]

**Comment by AidanLovelace** [comment]
I'm working on this now.

**Comment by Niko-sk2x** [comment]
This is not as easy as it may seem. CubeDistanceGraph doesn't really work that way.

**Comment by AidanLovelace** [comment]
What would be the best way to store a vertical view distance client side? Forge config file? options.txt?

**Comment by NotStirred** [comment]
1.12.2 had it in config/cubicchunks.cfg as `I:verticalCubeLoadDistance`

**Comment by AidanLovelace** [comment]
Ok, I'll do that for now.

**Comment by NotStirred** [comment]
This is quite a lot of work to do for vertical view to work, good luck...

**Comment by AidanLovelace** [comment]
Would it be a bad idea to just use the EarlyConfig for now?

**Comment by NotStirred** [comment]
you can do, I'll be moving that stuff around later anyway

**Comment by Niko-sk2x** [comment]
The target is forge config file but there is a problem with that:

in 1.12.2 I could modify forge config from code and store it back. So I could have the vertical view distance slider modify the config value and store it.

Modifying config values from code is no longer possible. So right now just make some dummy setter and getter for it in the config object and leave it to figure out later.

**Comment by Niko-sk2x** [comment]
Correction: I read the code now and apparently sometime between last time I looked at it and now an option to set config values programatically has been added.

**Comment by AidanLovelace** [comment]
Well I suppose I'll create the config.

**Comment by Niko-sk2x** [comment]
And no you shouldn't use EarlyConfig for that. EarlyConfig has one purpose: configuring stuff for mixin and stuff that needs to be loaded arbitrarily early. Vertical view distance can be just standard forge client config.

**Comment by AidanLovelace** [comment]
![image](https://user-images.githubusercontent.com/23508878/84843382-5f68f980-b00d-11ea-93d2-a13e48d09e72.png)
Okay, I've got vertical view & render distance working. Sort of. This is a hack if you've ever seen one, so be aware, but I've got a prototype.

Commit: https://github.com/AidanLovelace/CubicChunks/commit/ed9d112e048a9c11cad10b4b6508d9b6bacf0072

**Comment by NotStirred** [comment]
Closed by #538

**Comment by NotStirred** [comment]
wait im an idiot

**Comment by NotStirred** [comment]
updated and merged in d41a712714c19754ed0d88ded0cc0550dae2c9a7
