### ISSUE TITLE
Investigate ChunkHolders being null with optimised cube loading

### ISSUE THREAD

**Issue by NotStirred** [Barteks2x/CubicChunks#530]
@Cyclonit 
613f0fae9c3f8547129613b4dc83880a3d413e78 seems to be the cause of this issue.

There are significant chunk loading issues when using optimised cube loading. 
The ChunkHolder is not set at all (always null), nothing is loading for the affected columns.
Moving to a new area will start generation in that new area.

**Comment by NotStirred** [comment]
This was fixed, but I can't for the life of me remember of find the commit that did. 
It was due to a duplicate method somewhere.

**Comment by CorgiTaco** [comment]
Turns out the issue persists: https://hatebin.com/zvngjroeru
