### ISSUE TITLE
Ability to modify height-based sky effects/fog

### ISSUE THREAD

**Issue by muzikbike** [Barteks2x/CubicChunks#542]
super low priority at the moment but probably advisable to add in the ability to change these before any semblance of custom world support is implemented.

- Normal sky
![2020-07-11_01 22 52](https://user-images.githubusercontent.com/52297970/87212490-aef1cb00-c316-11ea-88ac-cc2b5860fbb1.png)

- Bottom half of the skybox turning black below y=60 (#457)
![2020-07-11_01 22 54](https://user-images.githubusercontent.com/52297970/87212496-b913c980-c316-11ea-8370-fabb65b16661.png)

- Dark fog effect below y=0
![2020-07-11_01 22 57](https://user-images.githubusercontent.com/52297970/87212510-c7fa7c00-c316-11ea-9d40-736aa4d6d0cc.png)

**Comment by NotStirred** [comment]
pretty sure we're just going to disable that honestly.

**Comment by NotStirred** [comment]
Closing due to dropping 1.15/16, and 1.17 vanilla is expected to deal with this
