### ISSUE TITLE
Blocks below y=-512 act weirdly

### ISSUE THREAD

**Issue by muzikbike** [Barteks2x/CubicChunks#544]
Entities falling into them will jitter, and they cannot be targeted nor broken, even with explosions:
![2020-07-11_09 57 19](https://user-images.githubusercontent.com/52297970/87220596-1599d780-c35d-11ea-9c71-5d8791d7158f.png)

**Comment by NotStirred** [comment]
This is due to us using -512 to 512 as the "world height limits" in vanilla logic.
Fixed and closed by 4be3daacc8f7a006d55d78f2257dd36e94c078e9
