### ISSUE TITLE
Investigate Server Light always being 0, While Client Light reports the expected values

### ISSUE THREAD

**Issue by NotStirred** [Barteks2x/CubicChunks#548]
Lighting seems to be saved correctly, as before indev save was implemented even spawn lighting would be recalculated upon loading the world, this is now not the case.

**Comment by NotStirred** [comment]
To make this even more whack; running a dedicated server and connecting with a client shows Server Light and Client Light as the same, expected values.

**Comment by CursedFlames** [comment]
Closing this issue since lighting is now partially working.
