### ISSUE TITLE
Fix being kicked from the world above 30 million blocks

### ISSUE THREAD

**Issue by muzikbike** [Barteks2x/CubicChunks#553]
Currently it's not possible to teleport up this high due to #552, but this can be reproduced clearly with a NBT editor. Flying above this height will return the player to the multiplayer screen, instead of allowing the player to just move freely (especially since blocks will probably be allowed to exist up here once #525 is fixed).

![2020-07-23_19 30 46](https://user-images.githubusercontent.com/52297970/88325718-42ff6180-cd1d-11ea-8a01-df0ac4173599.png)
![2020-07-23_19 30 49](https://user-images.githubusercontent.com/52297970/88325723-42ff6180-cd1d-11ea-96ab-6b7e6da4def2.png)
![2020-07-23_19 31 02](https://user-images.githubusercontent.com/52297970/88325727-4397f800-cd1d-11ea-915f-97ac13c1ecd8.png)

This also affects vanilla: https://bugs.mojang.com/browse/MC-123587

Closely relates to #535 and can probably be fixed alongside it.

**Comment by sa-shiro** [comment]
Are you sure it's an CC world??
Using `/tp ~ 30000000 ~` as well as `/tp ~ 3E8 ~` works perfectly fine, even `/tp ~ 1E9 ~` works as it should 

![20200723_212749](https://user-images.githubusercontent.com/7215049/88330255-6d581b80-cd2b-11ea-84dd-ff2980b8d7cf.jpg)

**Comment by sa-shiro** [comment]
Oh wait it's 1.16.1 sorry then I ran the test on 1.12.2

Maybe next time mention it so people don't have to inspect the images first

**Comment by muzikbike** [comment]
21w13a fixes this entirely: https://bugs.mojang.com/browse/MC-219901
