### ISSUE TITLE
Fix pistons not pushing down at y=1

### ISSUE THREAD

**Issue by muzikbike** [Barteks2x/CubicChunks#565]
Also easily reproducible in vanilla, but much more of a problem in CC for obvious reasons. https://bugs.mojang.com/browse/MC-69876

![2020-07-26_16 07 42](https://user-images.githubusercontent.com/52297970/88482609-4c294200-cf5a-11ea-9402-2e16a0b1d43f.png)

Upward pushing interestingly seems to work just fine:
![2020-07-26_16 09 19](https://user-images.githubusercontent.com/52297970/88482632-70851e80-cf5a-11ea-9a64-f196e93b8140.png)

**Comment by muzikbike** [comment]
dang github is taking its sweet ass-time realising that this will be fixed by a pull request...

**Comment by muzikbike** [comment]
This is now fixed in the latest snapshot: https://bugs.mojang.com/browse/MC-69876

**Comment by muzikbike** [comment]
Behaviour is weirder in 1.16.2 - pistons don't seem to extend at all in mst directions between 0 and -4.

**Comment by NotStirred** [comment]
Closing due to dropping 1.15/16, and 1.17 vanilla is expected to deal with this
