### ISSUE TITLE
Cannot place 2-tall flowers at y=255 or above

### ISSUE THREAD

**Issue by muzikbike** [Barteks2x/CubicChunks#566]
Fix should probably be similar to the door one.

![2020-07-26_16 14 37](https://user-images.githubusercontent.com/52297970/88482738-3cf6c400-cf5b-11ea-8032-992d048274f2.png)

**Comment by CursedFlames** [comment]
Tested, and this appears to only occur in 1.16. Not sure if it's due to a vanilla change or a discrepancy between CC versions; I'll investigate further later.

**Comment by NotStirred** [comment]
Closed by #586
