### ISSUE TITLE
World border does not render below y=0 / above y=512

### ISSUE THREAD

**Issue by muzikbike** [Barteks2x/CubicChunks#584]
Very very low priority

![2020-08-06_03 02 30](https://user-images.githubusercontent.com/52297970/89482393-b085a600-d791-11ea-8cde-e8222525dc11.png)
![2020-08-06_03 03 48](https://user-images.githubusercontent.com/52297970/89482394-b1b6d300-d791-11ea-84ba-9b9fc8f97e70.png)

**Comment by NotStirred** [comment]
Closing due to dropping 1.15/16, and 1.17 vanilla is expected to deal with this

**Comment by muzikbike** [comment]
...and guess what just got fixed: https://bugs.mojang.com/browse/MC-198864
