### ISSUE TITLE
Fix biome/regional difficulty not showing up in F3 above y=255 / below y=0

### ISSUE THREAD

**Issue by muzikbike** [Barteks2x/CubicChunks#585]
Blocks and stuff can exist up here now, so these values can't really be discarded by the game like in vanilla. May tie into #509.
![2020-08-06_15 44 31](https://user-images.githubusercontent.com/52297970/89546084-11e25f00-d7fc-11ea-88d1-5120d093b1ae.png)
![2020-08-06_15 44 32](https://user-images.githubusercontent.com/52297970/89546089-13138c00-d7fc-11ea-9f7e-64213c1dc342.png)

**Comment by NotStirred** [comment]
Closing due to dropping 1.15/16, and 1.17 vanilla is expected to deal with this
