### ISSUE TITLE
OpenCubicChunks 1.12.2 Server IllegalStateException: Called begin() in unclean state! Did you forget to call end()?

### ISSUE THREAD

**Issue by ColaIan** [Barteks2x/CubicChunks#594]
# Version Information
Minecraft version:  1.12.2
CubicChunks version: CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all
Forge version:  forge-1.12.2-14.23.5.2854
Other mods (if applicable):  worldedit-forge-mc1.12.2-6.1.10-dist

# Steps to reproduce:
1. Create a Forge server with CubikChunks
2. The error comes up randomly
3. Server crashes

Expected Behavior: Server runs smoothly

Actual Behavior: Server Crash

Link to crash log (if applicable - use a site such as [hastebin](https://hastebin.com/):
https://hastebin.com/awukazedad.pl

**Comment by Niko-sk2x** [comment]
Please don't use hastebin for logs as they are deleted after some time. I can't view the log

**Comment by ColaIan** [comment]
> Please don't use hastebin for logs as they are deleted after some time. I can't view the log

Oh sorry for the inconvenience, let me reupload it

**Comment by ColaIan** [comment]
https://pastebin.com/raw/txE5a8Bv

**Comment by Niko-sk2x** [comment]
Most likely same as #596 so closing as duplicate.
