### ISSUE TITLE
OpenCubicChunks 1.12.2 Server ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ColaIan** [Barteks2x/CubicChunks#597]
# Version Information
Minecraft version:  1.12.2
CubicChunks version: CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all
Forge version:  forge-1.12.2-14.23.5.2854
Other mods (if applicable):  worldedit-forge-mc1.12.2-6.1.10-dist

# Steps to reproduce:
1. Create a Forge server with CubikChunks
2. The error comes up randomly
3. Server crashes

Expected Behavior: Server runs smoothly

Actual Behavior: Server Crash

Link to crash log (if applicable - use a site such as [hastebin](https://hastebin.com/):
https://pastebin.com/raw/0Rj9d0sp

**Comment by Niko-sk2x** [comment]
Most likely same as #596 so closing as duplicate
