### ISSUE TITLE
CC and worldpainter after new light fixes

### ISSUE THREAD

**Issue by KubiRemPL** [Barteks2x/CubicChunks#602]
# Version Information
Minecraft version:  1.12.2
Forge version:  Latest for this version
Other mods (if applicable):
   

MixinCompat
   MixinBootstrap
   0.0.1153.0 (compiled from github)
   (Only CC crash at start)

# Steps to reproduce:
1. Make some map in world painter CC plugin
2.  Try to join this world with CC 0.0.1153.0 

Expected Behavior: Normal world load

Actual Behavior: Crash

BTW  I am using OpenJ9 JVM

Link to crash log (if applicable - use a site such as [hastebin](https://hastebin.com/): 
https://hastebin.com/dudumadulu.yaml
Can't send the world cuz it's too big.

**Comment by NotStirred** [comment]
I cannot reproduce this on latest CC (1159)
What version of the world painter plugin are you using?

**Comment by NotStirred** [comment]
You are using the wrong version of CC, you need the `-all.jar`, you are using `CubicChunks-1.12.2-0.0.1153.0-SNAPSHOT.jar`

**Comment by KubiRemPL** [comment]
Yeah that was the wrong version of CC. So sorry then.
