### ISSUE TITLE
Cube/Chunk generation issue on changing render distance

### ISSUE THREAD

**Issue by NotStirred** [Barteks2x/CubicChunks#610]
This has gone unnoticed since 1.15 where we thought we'd fixed it
Chunk/Cube generation stops in a specific location after increasing render distance.

To reproduce:
1. Set render distance to something low (6)
2. join or create a world, let it load around you
3. increase your render distance to something higher (12)
4. fly in a direction for a short while

**Comment by kristibektashi** [comment]
How do you download/compile for 1.17?

**Comment by CursedFlames** [comment]
You don't.

**Comment by kristibektashi** [comment]
why tho? I just want to test it in 1.17

**Comment by CursedFlames** [comment]
I mean, you can build it yourself, but we're not gonna be providing support for a heavily in-dev version that isn't playable yet. Building it shouldn't be any different than building any other mod though.

**Comment by kristibektashi** [comment]
`gradlew build` fails tho

**Comment by kristibektashi** [comment]
It is also missing a version number

**Comment by Niko-sk2x** [comment]
This may be fixed now. Is this actually still an issue?

**Comment by NotStirred** [comment]
Tested latest MC_1.17 as of now 3be75eb6ad77e5419a2f62ae9269cdf775a85fb1
This exact issue is now gone, now another similar issue is shown, upon doing the same steps client (even on internal server) is not sent the chunks in the newly loaded region. I have only gotten this to work for larger differences in render distance (6->17) and most consistently on loading into a new world.
Several minutes of waiting and the chunks do not load, F3-A and placing blocks inside them also no change. Server has them as I'm getting server collision checking

**Comment by Niko-sk2x** [comment]
Is it possible to find exact steps to reproduce the issue? (teleport to a given position, save and exit, load the world, go to a different position, chunks at that position not loading)

**Comment by NotStirred** [comment]
yes the original issue message says how to do so, though I found more success going from `6h` to `17h` view distances in my more recent testing
