### ISSUE TITLE
Rendering Overviewer Maps

### ISSUE THREAD

**Issue by KarmCraft** [Barteks2x/CubicChunks#611]
I am trying to generate Google Maps-style maps with the [Overviewer Mod](https://github.com/overviewer/Minecraft-Overviewer) in a CubicChunks generated world (build-the-earth.net project). The mod is not compatible with CC.. I forked the Overviewer project and am trying to make the necessary changes there.  

Can someone point me in the right direction on what are the main differences between .3dr files versus the default .mca files?
So far I have seen that the naming schema of .3dr files is "-1.-1.-1.3dr" instead of "r.-1.-1.mca" so it looks like they have 3 coordinates instead of 2. I don't know much else about the serialization in these files.

Is there a tool to read the files in cleartext?

Thanks in advance

**Comment by Niko-sk2x** [comment]
There is no such tool currently. But I provided a good explanation of the data format somewhere in a github issue for Amulet map editor (I will look it up and find it tomorrow).

**Comment by KarmCraft** [comment]
I've noticed there is a CubicChunksConverter tool, could I use this to convert the CC map to vanilla? Would the heights remain preserved?

**Comment by NotStirred** [comment]
The explanation Barteks2x was talking about is [here](https://github.com/Amulet-Team/Amulet-Map-Editor/issues/12#issuecomment-600105951)

The converter outputs 256 tall slices of a world, so unless the overviewer mod supports dimension stacking in some way, it wouldn't work
