### ISSUE TITLE
New build height settings in 20w49a (1.17)

### ISSUE THREAD

**Issue by kristibektashi** [Barteks2x/CubicChunks#612]
Since snapshot 20w19a added official support for heights in the range of -2048/2048 for customized worlds maybe that will help with this mod for 1.17?

**Comment by NotStirred** [comment]
If you have questions please join the CC discord server [here](https://discord.gg/kMfWg9m). This is an issue tracker not a forum for questions.

**Comment by CorgiTaco** [comment]
Yes it is already helping us vastly as we're taking advantage of said settings now on all 1.17 branches. Also gonna close this as this isn't exactly an issue.
