### ISSUE TITLE
1.16.4 version in curseforge?

### ISSUE THREAD

**Issue by kristibektashi** [Barteks2x/CubicChunks#615]
# Version Information
Minecraft version:  
Forge version:  
Other mods (if applicable):  

# Steps to reproduce:
1. 
2. 
3. 

Expected Behavior:

Actual Behavior:

Link to crash log (if applicable - use a site such as [hastebin](https://hastebin.com/):

**Comment by Niko-sk2x** [comment]
These versions are still in development, not ready for general use yet. Update for newer MC version will be released when it's ready.
