### ISSUE TITLE
cannot download

### ISSUE THREAD

**Issue by Ryzenicks** [Barteks2x/CubicChunks#626]
# Version Information
Minecraft version:  
Forge version:  
Other mods (if applicable):  

# Steps to reproduce:
1. 
2. 
3. 

Expected Behavior:

Actual Behavior:

Link to crash log (if applicable - use a site such as [hastebin](https://hastebin.com/):

**Comment by NotStirred** [comment]
don't open random issues with no description, if you have a question come to the discord server
