### ISSUE TITLE
Sand and other falling blocks dont fall below y:0

### ISSUE THREAD

**Issue by xcube16** [Barteks2x/CubicChunks#64]
Falling blocks also turn into items way to quickly under y:0

**Comment by Barteks2x** [comment]
sand turns into item after X ticks of falling, don't remember the exact number. It's vanilla behavior.

As for not falling below y=0 - there is probably hardcoded height check somewhere.

**Comment by Barteks2x** [comment]
Fixed sand turning into item too quickly in https://github.com/Barteks2x/CubicChunks/commit/2ead63bbce09f180efebd09d6aa3aa9eb05aa1f2

**Comment by Cyclonit** [comment]
https://www.youtube.com/watch?v=pRc3AIvLpiU

Falling entities are caught in a loop when falling outside of the range of loaded cubes.

**Comment by actioninja** [comment]
I found part of the offending code in BlockFalling
` private void checkFallable(World worldIn, BlockPos pos)
    {
        if ((worldIn.isAirBlock(pos.down()) || canFallThrough(worldIn.getBlockState(pos.down()))) && pos.getY() >= 0) `
Part of the check for "should fall" is if the block is above Y: 0.

The entity code doesn't seem to have any other hardcoded checks so the falling entity loop may require a rework of falling logic.

**Comment by Niko-sk2x** [comment]
It's not that hard to find and fix, it just isn't a high priority issue right now.

There may be also issues with sand disappearing after falling into unloaded chunks - this is vanilla bug (vanilla has such issue in horizontal direction)
