### ISSUE TITLE
java.lang.NullPointerException: Exception in server tick loop crash when loading world

### ISSUE THREAD

**Issue by Sheikanery** [Barteks2x/CubicChunks#641]
# Version Information
Minecraft version:  1.12.2
Forge version:  14.23.5.2854
Other mods (if applicable):  Minecraft Coder Pack, Forge mod loader, Minecraft Forge 

# Steps to reproduce:
1. Download world file from https://drive.google.com/file/d/1W104p5cMm3_NKE72E9AxwwRDp2KcNgYM/view
2. Put into world folder
3. Press play selected world

Expected Behavior: The world to be playable

Actual Behavior: Instantly crashing to the launcher with the error listed in the title.

[Link to crash log](https://pastebin.com/MJPe12cZ)

**Comment by NotStirred** [comment]
Could you post the entire `latest.log` or `debug.log` for the crash?
Sadly the crash report leaves out a lot of information

**Comment by Niko-sk2x** [comment]
This means you have some corrupted chunks in your world, most likely caused by minecraft process being stopped while saving chunks. You can try to remove the corrupted chunks using this https://github.com/OpenCubicChunks/WorldFixer/releases/tag/1.8-SNAPSHOT
