### ISSUE TITLE
instant crash

### ISSUE THREAD

**Issue by PC1up** [Barteks2x/CubicChunks#643]
# Version Information
Minecraft version:  1.12.2
Forge version:  1.12.2
Other mods (if applicable):  

# Steps to reproduce:
1. Load "CubicChunks-1.12.2-0.0.970.0-SNAPSHOT-all" into your mods folder
2. Start Minecraft with Forge 1.12.2
3. it should crash immediately

Expected Behavior: not crashing

Actual Behavior: crashing

Link to crash log (if applicable - use a site such as [hastebin](https://hastebin.com/): https://paste.md-5.net/nunugasoru.sql
Screenshot of mods folder: https://prnt.sc/10qy8t7

**Comment by NotStirred** [comment]
This is a nearly 2 year old version of CC, please try with latest recommended (as of now it's `1185`)
If you still have problems reopen this issue

**Comment by PC1up** [comment]
uhm where do I get the newest version as Java-file from?

**Comment by NotStirred** [comment]
If you join the discord server there is an announcement with every new release. This is latest as of now: [1185](https://cdn.discordapp.com/attachments/576216724257374208/807488494074593310/CubicChunks-1.12.2-0.0.1185.0-SNAPSHOT-all.jar)
