### ISSUE TITLE
[1.17] NaturalSpawner Mixin fails to apply in release builds

### ISSUE THREAD

**Issue by andrewathalye** [Barteks2x/CubicChunks#660]
The createCubicState injector fails to apply in release builds (non-dev) due to asLong(II)J not being defined in CubePos in the intermediary naming scheme. This appears to be a result of Vec3i being CubePos' parent, and while an obfuscation mapping is defined in Yarn for Vec3i, no such mapping exists for CubePos itself, fooling the Injector.

This can be reversed manually by replacing asLong(II)J with method_8331(II)J, but it may be more desirable to manually specify method_8331(II)J as the obfuscated name or take some other approach to the ASM transformer which avoids relying on asLong(II)J.

**Comment by CorgiTaco** [comment]
What release build are you on about? Could you link it?

**Comment by andrewathalye** [comment]
Sorry, by release I meant build using intermediary mappings fresh from the branch (as opposed to named mappings) , not as in a full release. As far as I am aware there are not yet any prebuilt releases for 1.17.

**Comment by Niko-sk2x** [comment]
There are no published jars yet because the mod is not ready to be used yet so testing outside of dev environment is not a priority right now.

The real fix is to handle the rename in `MainTransformer`, so by the time mixin is applied, the name is already stable.

**Comment by NotStirred** [comment]
Corgi said it was fixed, closing. Blame him if there is still an issue
