### ISSUE TITLE
I need help, idk if its mod incompatibility or smth.

### ISSUE THREAD

**Issue by Calebplaysgames** [Barteks2x/CubicChunks#717]
# Version Information
Minecraft version:  
Forge version:  
Other mods (if applicable):  
https://pastebin.com/HTAb7iZu
# Steps to reproduce:
1. load mods.
2. 
3. 

Expected Behavior:
supposed to not crash.
Actual Behavior:
https://pastebin.com/HTAb7iZu crashes with no errors.
Link to crash log (if applicable - use a site such as [hastebin](https://hastebin.com/):
https://pastebin.com/HTAb7iZu

**Comment by Niko-sk2x** [comment]
This is fixed in latest version. Will be available in next update.
