### ISSUE TITLE
Crash with video settings menu

### ISSUE THREAD

**Issue by Desoroxxx** [Barteks2x/CubicChunks#738]
# Version Information
Minecraft version: 1.12.2
Forge version: 14.23.5.2855
Other mods: You can watch in crash report but I cannot list them, but I will list Optifine 1.12.2_HD_U_G5

# Steps to reproduce:
1. Install Optifine 1.12.2_HD_U_G5
2. Launch game
3. Go to video settings and enjoy crash

Expected Behavior:

Display the video settings menu

Actual Behavior:

Crashing

Link to crash log: https://hastebin.com/yoriyefema.rb

**Comment by Desoroxxx** [comment]
I need to precise that except the video settings menu, everything works

**Comment by AsheX1** [comment]
dit you ever change the video settings

**Comment by AsheX1** [comment]
try  deleting the "'optionsof.txt" in the minecraft folder to reset optifine settings

**Comment by Desoroxxx** [comment]
I am going to try this, I will reply the result shortly

**Comment by Desoroxxx** [comment]
I deleted the "optionsof.txt" file and it still crashed

**Comment by AsheX1** [comment]
is there any other mod that changes something about lights and stuff
also dit the video setting worked before installing optifine

**Comment by Desoroxxx** [comment]
Okay the video setting work without optifine

**Comment by AsheX1** [comment]
mmmmm may need to remove mods and see what is making the problem happen

and stuff back in 1 by 1

**Comment by Desoroxxx** [comment]
Let's go through 165 mods, lol I will be back to say any relevant news, I am going to try stuff that might relate first

**Comment by AsheX1** [comment]
also your CC is outdated  
https://cdn.discordapp.com/attachments/576216724257374208/884231762618769428/CubicChunks-1.12.2-0.0.1204.0-SNAPSHOT-all.jar

**Comment by AsheX1** [comment]
the last version for CC is on the discord dont know about the curse forge page

**Comment by Desoroxxx** [comment]
Thanks going to try it maybe it fix it, and I downloaded the latest on Curse Forge

**Comment by AsheX1** [comment]
ya barteks a bit lazy on updating it

**Comment by AsheX1** [comment]
seems CWG is also outdated on curseforge here is the last version from discord
https://cdn.discordapp.com/attachments/576216724257374208/862094973373644810/CubicWorldGen-1.12.2-0.0.151.0-SNAPSHOT-all.jar

**Comment by Desoroxxx** [comment]
Okay after further investigation without any mods except optifine and cubic chunks my video settings menu look completly different and work

**Comment by AsheX1** [comment]
also update CWG on last comment i posted as that was also outdated on curseforge

**Comment by Desoroxxx** [comment]
I did

**Comment by AsheX1** [comment]
if you find the incompatible mod post it in #448

**Comment by Desoroxxx** [comment]
Finally!!!

It was Vanilla Fix and Smooth Scrolling Everywhere.

**Comment by NotStirred** [comment]
cannot reproduce with optifine `G5`, Smooth crolling everywhere `1.1`, cc `1204` and forge `2855`

**Comment by NotStirred** [comment]
cannot reproduce with optifine `G5`, Smooth scrolling everywhere `1.1`, cc `1204` and forge `2855` and vanillafix `1.0.10-150`

**Comment by Desoroxxx** [comment]
Hmmm very weird, because I tested it and both created problem, so I guess there might be another factor that make it crash
