### ISSUE TITLE
Optifine crashes the game when cubic chunk is present

### ISSUE THREAD

**Issue by ceketrum** [Barteks2x/CubicChunks#742]
Hello I am developing a modpack and I notice some problem between optifine and cubic chunk!My games crash when the 2 mods are present while independently it works very well. Please give me an answer as soon as possible to overcome this problem.

**Comment by BaccarWozat** [comment]
What does the crash log say? Which version of Optifine are you using?

**Comment by ceketrum** [comment]
i am using the version OptiFine-1.12.2_HD_U_G5.jar . 

here is the crash report : https://pastebin.com/YbShU3CG

**Comment by Niko-sk2x** [comment]
Update cubic chunks to latest version.

**Comment by ceketrum** [comment]
Ah yes indeed thank you I downloaded the version available on t-luncher .... It must not be up to date
