### ISSUE TITLE
VirusTotal detecting mod as trojan.

### ISSUE THREAD

**Issue by RandomGuy25** [Barteks2x/CubicChunks#743]
Good Morning. I downloaded this mod and i scanned it with VirusTotal for safety, and it detected a trojan. I don't know what to do with this mod. Should i ignore it and use it anyway?
![Screen](https://user-images.githubusercontent.com/95925756/145594481-afd04c8e-dba8-45da-9b42-103a0d585eb3.png)

**Comment by AsheX1** [comment]
VirusTotal is useless.
This is not a problem also dit you download it of curseforge or the discord server

**Comment by RandomGuy25** [comment]
> VirusTotal is useless. This is not a problem also dit you download it of curseforge or the discord server

I downloaded it from curseforge.

**Comment by AsheX1** [comment]
dont worry about it you are all good

**Comment by RandomGuy25** [comment]
Okay, thanks for help.

**Comment by Niko-sk2x** [comment]
Its likely considered a "virus" as it transforms java bytecode at runtime triggering some heuristics in some antimalware software, but i will verify it myself.

**Comment by RandomGuy25** [comment]
> Its likely considered a "virus" as it transforms java bytecode at runtime triggering some heuristics in some antimalware software, but i will verify it myself.

Okay.

**Comment by Niko-sk2x** [comment]
I confirmed it does in fact show as a false positive so everything is fine.

**Comment by Niko-sk2x** [comment]
It's no longer marked as malicious by virustotal.

After selecting an option to scan the file again it was no longer detected as a trojan.

**Comment by RandomGuy25** [comment]
> It's no longer marked as malicious by virustotal.
> 
> After selecting an option to scan the file again it was no longer detected as a trojan.

Okay, thank you.

**Comment by NotStirred** [comment]
Oh my god that's hilarious, though as you said it's not surprising with the transformation going on that it was a false positive
