### ISSUE TITLE
Game freezes leaving world

### ISSUE THREAD

**Issue by idkimanerd** [Barteks2x/CubicChunks#745]
Modlist:
CreativeCore_v1.10.69_mc1.12.2
CubicChunks-1.12.2-0.0.1215.0-SNAPSHOT-all
jei_1.12.2-4.16.1.301
LittleTiles_v1.5.57_mc1.12.2

When I hit save and quit, the game is stuck. In task manager it is using he same amount of memory the whole time and using 0% CPU.
https://pastebin.com/yvxAb70B Latest

**Comment by AsheX1** [comment]
update last CC version now is 1224 its on the CC discord

**Comment by idkimanerd** [comment]
OK thank you
