### ISSUE TITLE
Is it possible to create a dimension without chunks?

### ISSUE THREAD

**Issue by Titlehhhh** [Barteks2x/CubicChunks#750]
Your mod increases the number of chunks, but how to do the opposite?
I wanted to create an empty dimension (galaxy space) without chunks. 3D space and nothing more.

**Comment by Gaming32** [comment]
That would be 3D empty though. Create a void world, then the only way to place blocks is using the `/setblock` command (and related commands).

**Comment by Titlehhhh** [comment]
I was thinking about creating a space mod and I would like to create space as a separate dimension.

**Comment by Titlehhhh** [comment]
I need to understand how to do this at the code level.

**Comment by NotStirred** [comment]
As already suggested, you should make a void dimension, then you can add asteroids or whatever to that

If you have "no chunks" that means: blocks, mobs, players all can't exist in the world.
