### ISSUE TITLE
Height limit 256 blocks error won't go away ON SERVER

### ISSUE THREAD

**Issue by ghost** [Barteks2x/CubicChunks#755]
### **I KNOW THIS IS IN THE FAQ OF THE MOD!!! IT DOESN'T SAY WHAT TO DO WITH SERVERS THOUGH!!!!**
# Version Information
Minecraft version:  1.12.2
Forge version: 14.23.5.2859
Other mods (if applicable):  
CubicWorldGen
Terra 1 to 1

# Steps to reproduce:
1. Make forge server with cubic chunks (I used Aternos for server hosting so that might be the issue, probably not though)
2. Install terra 1 to 1 mod and cubic world gen
3. Try building in high places (above the height limit of normal vanilla)
4. See the error
5. Try reconnecting
6. Still see the error
7. Restart the server (it says to save and quit in the faq so I did the most similar thing possible)
8. Still see the error

Expected Behavior:
I can build above Y level 256 on a server.
Actual Behavior:
I need to use commands to place blocks.

Link to crash log (if applicable - use a site such as [hastebin](https://hastebin.com/):
It didn't crash

**Comment by NotStirred** [comment]
what worldtype is the world? Are you certain you made it `CustomCubic` in the server's config?

I'd recommend following [this guide in the discord server](https://discord.com/channels/316679487955927050/338265853185490945/478385902993932288)

**Comment by ghost** [comment]
I'm using the terra 1 to 1 mod so I used that mod's world type, which should normally work fine as the mod requires cubic chunks

**Comment by Niko-sk2x** [comment]
Change it in server.properties

**Comment by ghost** [comment]
Change what?

**Comment by ghost** [comment]
Oh I was changing the max world size of the server not the build height, not a bug. Closed
