### ISSUE TITLE
Gradle build failed: Could not initialize class org.codehaus.groovy.reflection.ReflectionCache

### ISSUE THREAD

**Issue by Atten007** [Barteks2x/CubicChunks#762]
# Version Information
Minecraft version: 1.16.5
Forge version: 36.2.39
Other mods (if applicable): None 

# Steps to reproduce:
1. Clone the MC_1.16 branch with "git clone -b MC_1.16"
2. Then "cd CubicChunks"
3. Now execute "./gradlew build"
4. It'll fail with a Could not initialize class org.codehaus.groovy.reflection.ReflectionCache error.

Expected Behavior:

The build should be successful instead of failing.

Actual Behavior:

The build has failed.

Link to crash log (if applicable - use a site such as [hastebin](https://hastebin.com/): None

**Comment by Niko-sk2x** [comment]
This is likely caused by using too new java version. And 1.16.x isn't and won't be supported. We switched all development to 1.17 snapshots very early.
