### ISSUE TITLE
Sponge server + cubicchunk

### ISSUE THREAD

**Issue by StalkerStrela** [Barteks2x/CubicChunks#772]
# Version Information
Minecraft version:  1.12.2 server 
Forge version:  forge-1.12.2-14.23.5.2859.jar
sponge: spongeforge-1.12.2-2838-7.4.7.jar
When I tried to use Spongeforge with Cubachunk it crashes
[debug.log](https://github.com/OpenCubicChunks/CubicChunks/files/12587233/debug.log)
When I'm without a spongeforge, it doesn't crumble.

**Comment by NotStirred** [comment]
CC doesn't and likely never will support sponge unfortunately
