### ISSUE TITLE
Using in server

### ISSUE THREAD

**Issue by bryanirp** [Barteks2x/CubicChunks#777]
# Version Information
Minecraft version:  1.2.2
Forge version:  forge-1.12.2-14.23.5.2859
Other mods (if applicable):  

# Steps to reproduce:
1. Start a forge servers, then add the mod to mods file
2. Join to server
3. Start to build vertically

Expected Behavior: No 256 limit

Actual Behavior: 256 limit

Comment: I just wanna build big skycrapper with my friends, but there's just cubic chunks rendering, with 256 blocks limit

**Comment by Niko-sk2x** [comment]
Please read the `Creating Cubic Chunks world` section on curseforge page:
![image](https://github.com/OpenCubicChunks/CubicChunks/assets/1349112/69b697f7-4291-4b8c-a376-b19a54d837c5)

(actually just realized it's slightly outdated - it needs to be set to `NEW_WORLD`, not true - comments in the file explain it)
